/* Generated by Yosys 0.63 (git sha1 3bc26ff4d055adfbba8b424508ab4a36405ffc0b, g++ 15.2.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

(* top =  1  *)
(* src = "src/UART_rxtx.v:4.1-31.10" *)
module Combined_RXTX(rx, clkgen, reset, tx_enable, \data_tx[0] , \data_tx[1] , \data_tx[2] , \data_tx[3] , \data_tx[4] , \data_tx[5] , \data_tx[6] , \data_tx[7] , tx, parity_err, error_flag, rx_done, \data_rx[0] , \data_rx[1] , \data_rx[2] , \data_rx[3] , \data_rx[4] 
, \data_rx[5] , \data_rx[6] , \data_rx[7] );
  (* src = "src/UART_rxtx.v:5.16-5.18" *)
  input rx;
  wire rx;
  (* src = "src/UART_rxtx.v:5.20-5.26" *)
  input clkgen;
  wire clkgen;
  (* src = "src/UART_rxtx.v:5.28-5.33" *)
  input reset;
  wire reset;
  (* src = "src/UART_rxtx.v:5.35-5.44" *)
  input tx_enable;
  wire tx_enable;
  (* src = "src/UART_rxtx.v:6.22-6.29" *)
  input \data_tx[0] ;
  wire \data_tx[0] ;
  (* src = "src/UART_rxtx.v:6.22-6.29" *)
  input \data_tx[1] ;
  wire \data_tx[1] ;
  (* src = "src/UART_rxtx.v:6.22-6.29" *)
  input \data_tx[2] ;
  wire \data_tx[2] ;
  (* src = "src/UART_rxtx.v:6.22-6.29" *)
  input \data_tx[3] ;
  wire \data_tx[3] ;
  (* src = "src/UART_rxtx.v:6.22-6.29" *)
  input \data_tx[4] ;
  wire \data_tx[4] ;
  (* src = "src/UART_rxtx.v:6.22-6.29" *)
  input \data_tx[5] ;
  wire \data_tx[5] ;
  (* src = "src/UART_rxtx.v:6.22-6.29" *)
  input \data_tx[6] ;
  wire \data_tx[6] ;
  (* src = "src/UART_rxtx.v:6.22-6.29" *)
  input \data_tx[7] ;
  wire \data_tx[7] ;
  (* src = "src/UART_rxtx.v:7.17-7.19" *)
  output tx;
  wire tx;
  (* src = "src/UART_rxtx.v:7.21-7.31" *)
  output parity_err;
  wire parity_err;
  (* src = "src/UART_rxtx.v:7.33-7.43" *)
  output error_flag;
  wire error_flag;
  (* src = "src/UART_rxtx.v:7.45-7.52" *)
  output rx_done;
  wire rx_done;
  (* src = "src/UART_rxtx.v:8.23-8.30" *)
  output \data_rx[0] ;
  wire \data_rx[0] ;
  (* src = "src/UART_rxtx.v:8.23-8.30" *)
  output \data_rx[1] ;
  wire \data_rx[1] ;
  (* src = "src/UART_rxtx.v:8.23-8.30" *)
  output \data_rx[2] ;
  wire \data_rx[2] ;
  (* src = "src/UART_rxtx.v:8.23-8.30" *)
  output \data_rx[3] ;
  wire \data_rx[3] ;
  (* src = "src/UART_rxtx.v:8.23-8.30" *)
  output \data_rx[4] ;
  wire \data_rx[4] ;
  (* src = "src/UART_rxtx.v:8.23-8.30" *)
  output \data_rx[5] ;
  wire \data_rx[5] ;
  (* src = "src/UART_rxtx.v:8.23-8.30" *)
  output \data_rx[6] ;
  wire \data_rx[6] ;
  (* src = "src/UART_rxtx.v:8.23-8.30" *)
  output \data_rx[7] ;
  wire \data_rx[7] ;
  (* hdlname = "M_RX_0 clkin" *)
  (* src = "src/UART_rx.v:7.25-7.30" *)
  wire \M_RX_0.clkin ;
  (* hdlname = "M_RX_0 data_counter" *)
  (* src = "src/UART_rx.v:21.48-21.60" *)
  reg \M_RX_0.data_counter[0] ;
  (* src = "src/UART_rx.v:80.1-169.4" *)
  wire \M_RX_0.data_counter[0]_$_DFFE_PN1P__Q_D ;
  (* hdlname = "M_RX_0 data_counter" *)
  (* src = "src/UART_rx.v:21.48-21.60" *)
  reg \M_RX_0.data_counter[1] ;
  (* src = "src/UART_rx.v:80.1-169.4" *)
  wire \M_RX_0.data_counter[1]_$_DFFE_PN1P__Q_D ;
  wire \M_RX_0.data_counter[1]_$_NOR__A_Y ;
  wire \M_RX_0.data_counter[1]_$_XNOR__A_Y ;
  (* hdlname = "M_RX_0 data_counter" *)
  (* src = "src/UART_rx.v:21.48-21.60" *)
  reg \M_RX_0.data_counter[2] ;
  (* src = "src/UART_rx.v:80.1-169.4" *)
  wire \M_RX_0.data_counter[2]_$_DFFE_PN1P__Q_D ;
  wire \M_RX_0.data_counter[2]_$_DFFE_PN1P__Q_D_$_OR__Y_A ;
  (* hdlname = "M_RX_0 data_counter" *)
  (* src = "src/UART_rx.v:21.48-21.60" *)
  reg \M_RX_0.data_counter[3] ;
  (* src = "src/UART_rx.v:80.1-169.4" *)
  wire \M_RX_0.data_counter[3]_$_DFFE_PN0P__Q_D ;
  wire \M_RX_0.data_counter[3]_$_DFFE_PN0P__Q_D_$_ANDNOT__Y_A ;
  wire \M_RX_0.data_counter[3]_$_DFFE_PN0P__Q_D_$_ANDNOT__Y_A_$_XOR__Y_A ;
  wire \M_RX_0.data_counter[3]_$_NOR__A_Y ;
  wire \M_RX_0.data_counter[3]_$_OR__A_Y ;
  wire \M_RX_0.data_counter[3]_$_OR__A_Y_$_MUX__S_Y ;
  (* hdlname = "M_RX_0 data_in" *)
  (* src = "src/UART_rx.v:7.16-7.23" *)
  wire \M_RX_0.data_in ;
  (* hdlname = "M_RX_0 data_out" *)
  (* src = "src/UART_rx.v:8.22-8.30" *)
  reg \M_RX_0.data_out[0] ;
  (* hdlname = "M_RX_0 data_out" *)
  (* src = "src/UART_rx.v:8.22-8.30" *)
  reg \M_RX_0.data_out[1] ;
  (* hdlname = "M_RX_0 data_out" *)
  (* src = "src/UART_rx.v:8.22-8.30" *)
  reg \M_RX_0.data_out[2] ;
  (* hdlname = "M_RX_0 data_out" *)
  (* src = "src/UART_rx.v:8.22-8.30" *)
  reg \M_RX_0.data_out[3] ;
  (* hdlname = "M_RX_0 data_out" *)
  (* src = "src/UART_rx.v:8.22-8.30" *)
  reg \M_RX_0.data_out[4] ;
  (* hdlname = "M_RX_0 data_out" *)
  (* src = "src/UART_rx.v:8.22-8.30" *)
  reg \M_RX_0.data_out[5] ;
  (* hdlname = "M_RX_0 data_out" *)
  (* src = "src/UART_rx.v:8.22-8.30" *)
  reg \M_RX_0.data_out[6] ;
  (* hdlname = "M_RX_0 data_out" *)
  (* src = "src/UART_rx.v:8.22-8.30" *)
  reg \M_RX_0.data_out[7] ;
  (* hdlname = "M_RX_0 error_flag" *)
  (* src = "src/UART_rx.v:10.16-10.26" *)
  wire \M_RX_0.error_flag ;
  (* hdlname = "M_RX_0 nextstate" *)
  (* src = "src/UART_rx.v:22.18-22.27" *)
  wire \M_RX_0.nextstate[0] ;
  wire \M_RX_0.nextstate[0]_$_ANDNOT__Y_B ;
  wire \M_RX_0.nextstate[0]_$_ANDNOT__Y_B_$_ANDNOT__Y_A ;
  wire \M_RX_0.nextstate[0]_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_B ;
  (* hdlname = "M_RX_0 nextstate" *)
  (* src = "src/UART_rx.v:22.18-22.27" *)
  wire \M_RX_0.nextstate[1] ;
  wire \M_RX_0.nextstate[1]_$_ORNOT__Y_A ;
  wire \M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_A ;
  wire \M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B ;
  wire \M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B_$_ANDNOT__Y_A ;
  wire \M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y ;
  wire \M_RX_0.nextstate[1]_$_ORNOT__Y_B ;
  wire \M_RX_0.nextstate[1]_$_ORNOT__Y_B_$_OR__Y_A ;
  wire \M_RX_0.nextstate[1]_$_ORNOT__Y_B_$_OR__Y_A_$_MUX__Y_B ;
  (* hdlname = "M_RX_0 nextstate" *)
  (* src = "src/UART_rx.v:22.18-22.27" *)
  wire \M_RX_0.nextstate[2] ;
  wire \M_RX_0.nextstate[2]_$_ANDNOT__Y_B ;
  wire \M_RX_0.nextstate[2]_$_ANDNOT__Y_B_$_ANDNOT__Y_A ;
  wire \M_RX_0.nextstate[2]_$_ANDNOT__Y_B_$_ANDNOT__Y_B ;
  (* hdlname = "M_RX_0 parity_err" *)
  (* src = "src/UART_rx.v:10.37-10.47" *)
  wire \M_RX_0.parity_err ;
  (* hdlname = "M_RX_0 reset" *)
  (* src = "src/UART_rx.v:7.32-7.37" *)
  wire \M_RX_0.reset ;
  (* hdlname = "M_RX_0 rx" *)
  (* src = "src/UART_rx.v:23.6-23.8" *)
  reg \M_RX_0.rx ;
  (* hdlname = "M_RX_0 rx_done" *)
  (* src = "src/UART_rx.v:10.28-10.35" *)
  wire \M_RX_0.rx_done ;
  (* hdlname = "M_RX_0 rx_prev" *)
  (* src = "src/UART_rx.v:23.10-23.17" *)
  reg \M_RX_0.rx_prev ;
  wire \M_RX_0.rx_prev_$_ANDNOT__A_Y ;
  wire \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_A ;
  wire \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_A_$_ANDNOT__A_Y ;
  wire \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_A_$_ANDNOT__A_Y_$_ANDNOT__A_Y ;
  wire \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_A_$_OR__Y_A ;
  wire \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_A_$_OR__Y_A_$_ANDNOT__B_Y ;
  wire \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_Y ;
  wire \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_Y_$_ANDNOT__B_A ;
  wire \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_Y_$_ANDNOT__B_Y ;
  wire \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_Y_$_ANDNOT__B_Y_$_ANDNOT__A_B ;
  wire \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_Y_$_ANDNOT__B_Y_$_ANDNOT__A_Y ;
  (* hdlname = "M_RX_0 sample_counter" *)
  (* src = "src/UART_rx.v:21.11-21.25" *)
  reg \M_RX_0.sample_counter[0] ;
  (* hdlname = "M_RX_0 sample_counter" *)
  (* src = "src/UART_rx.v:21.11-21.25" *)
  reg \M_RX_0.sample_counter[1] ;
  wire \M_RX_0.sample_counter[1]_$_OR__A_Y ;
  wire \M_RX_0.sample_counter[1]_$_OR__A_Y_$_MUX__A_Y ;
  wire \M_RX_0.sample_counter[1]_$_OR__A_Y_$_OR__A_Y ;
  wire \M_RX_0.sample_counter[1]_$_OR__A_Y_$_OR__A_Y_$_OR__A_Y ;
  wire \M_RX_0.sample_counter[1]_$_XOR__A_Y ;
  (* hdlname = "M_RX_0 sample_counter" *)
  (* src = "src/UART_rx.v:21.11-21.25" *)
  reg \M_RX_0.sample_counter[2] ;
  wire \M_RX_0.sample_counter[2]_$_XNOR__B_Y ;
  (* hdlname = "M_RX_0 sample_counter" *)
  (* src = "src/UART_rx.v:21.11-21.25" *)
  reg \M_RX_0.sample_counter[3] ;
  wire \M_RX_0.sample_counter[3]_$_OR__B_Y ;
  wire \M_RX_0.sample_counter[3]_$_XNOR__B_A ;
  wire \M_RX_0.sample_counter[3]_$_XNOR__B_A_$_ANDNOT__Y_A ;
  wire \M_RX_0.sample_counter[3]_$_XNOR__B_Y ;
  (* hdlname = "M_RX_0 sample_counter_next" *)
  (* src = "src/UART_rx.v:21.27-21.46" *)
  wire \M_RX_0.sample_counter_next[0] ;
  wire \M_RX_0.sample_counter_next[0]_$_OR__Y_A ;
  wire \M_RX_0.sample_counter_next[0]_$_OR__Y_A_$_OR__Y_A ;
  wire \M_RX_0.sample_counter_next[0]_$_OR__Y_A_$_OR__Y_A_$_ANDNOT__Y_B ;
  wire \M_RX_0.sample_counter_next[0]_$_OR__Y_A_$_OR__Y_B ;
  wire \M_RX_0.sample_counter_next[0]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_A ;
  wire \M_RX_0.sample_counter_next[0]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_A_$_ANDNOT__Y_B ;
  wire \M_RX_0.sample_counter_next[0]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_B ;
  (* hdlname = "M_RX_0 sample_counter_next" *)
  (* src = "src/UART_rx.v:21.27-21.46" *)
  wire \M_RX_0.sample_counter_next[1] ;
  wire \M_RX_0.sample_counter_next[1]_$_OR__Y_A ;
  wire \M_RX_0.sample_counter_next[1]_$_OR__Y_A_$_OR__Y_A ;
  wire \M_RX_0.sample_counter_next[1]_$_OR__Y_A_$_OR__Y_A_$_ANDNOT__Y_B ;
  wire \M_RX_0.sample_counter_next[1]_$_OR__Y_A_$_OR__Y_B ;
  wire \M_RX_0.sample_counter_next[1]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_A ;
  wire \M_RX_0.sample_counter_next[1]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_A_$_ANDNOT__Y_B ;
  wire \M_RX_0.sample_counter_next[1]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_B ;
  (* hdlname = "M_RX_0 sample_counter_next" *)
  (* src = "src/UART_rx.v:21.27-21.46" *)
  wire \M_RX_0.sample_counter_next[2] ;
  wire \M_RX_0.sample_counter_next[2]_$_OR__Y_A ;
  wire \M_RX_0.sample_counter_next[2]_$_OR__Y_A_$_OR__Y_A ;
  wire \M_RX_0.sample_counter_next[2]_$_OR__Y_A_$_OR__Y_A_$_ANDNOT__Y_B ;
  wire \M_RX_0.sample_counter_next[2]_$_OR__Y_A_$_OR__Y_B ;
  wire \M_RX_0.sample_counter_next[2]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_A ;
  wire \M_RX_0.sample_counter_next[2]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_A_$_ANDNOT__Y_B ;
  wire \M_RX_0.sample_counter_next[2]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_B ;
  (* hdlname = "M_RX_0 sample_counter_next" *)
  (* src = "src/UART_rx.v:21.27-21.46" *)
  wire \M_RX_0.sample_counter_next[3] ;
  wire \M_RX_0.sample_counter_next[3]_$_NOR__Y_A ;
  wire \M_RX_0.sample_counter_next[3]_$_NOR__Y_A_$_ANDNOT__Y_A ;
  wire \M_RX_0.sample_counter_next[3]_$_NOR__Y_A_$_ANDNOT__Y_A_$_ANDNOT__Y_A ;
  wire \M_RX_0.sample_counter_next[3]_$_NOR__Y_A_$_ANDNOT__Y_A_$_ANDNOT__Y_B ;
  wire \M_RX_0.sample_counter_next[3]_$_NOR__Y_A_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_ANDNOT__Y_B ;
  wire \M_RX_0.sample_counter_next[3]_$_NOR__Y_A_$_ANDNOT__Y_B ;
  wire \M_RX_0.sample_counter_next[3]_$_NOR__Y_A_$_ANDNOT__Y_B_$_ANDNOT__Y_B ;
  (* hdlname = "M_RX_0 samplex16_counter" *)
  (* src = "src/UART_rx.v:20.11-20.28" *)
  reg \M_RX_0.samplex16_counter[0] ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  wire \M_RX_0.samplex16_counter[0]_$_DFF_PN0__Q_D ;
  (* hdlname = "M_RX_0 samplex16_counter" *)
  (* src = "src/UART_rx.v:20.11-20.28" *)
  reg \M_RX_0.samplex16_counter[1] ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  wire \M_RX_0.samplex16_counter[1]_$_DFF_PN1__Q_D ;
  wire \M_RX_0.samplex16_counter[1]_$_NOR__A_Y ;
  wire \M_RX_0.samplex16_counter[1]_$_XNOR__A_Y ;
  (* hdlname = "M_RX_0 samplex16_counter" *)
  (* src = "src/UART_rx.v:20.11-20.28" *)
  reg \M_RX_0.samplex16_counter[2] ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  wire \M_RX_0.samplex16_counter[2]_$_DFF_PN1__Q_D ;
  wire \M_RX_0.samplex16_counter[2]_$_DFF_PN1__Q_D_$_OR__Y_A ;
  (* hdlname = "M_RX_0 samplex16_counter" *)
  (* src = "src/UART_rx.v:20.11-20.28" *)
  reg \M_RX_0.samplex16_counter[3] ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  wire \M_RX_0.samplex16_counter[3]_$_DFF_PN0__Q_D ;
  wire \M_RX_0.samplex16_counter[3]_$_DFF_PN0__Q_D_$_NOR__Y_A ;
  wire \M_RX_0.samplex16_counter[3]_$_DFF_PN0__Q_D_$_NOR__Y_A_$_XNOR__Y_A ;
  wire \M_RX_0.samplex16_counter[3]_$_NOR__B_Y ;
  wire \M_RX_0.samplex16_counter[3]_$_OR__B_Y ;
  (* hdlname = "M_RX_0 samplex16_counter" *)
  (* src = "src/UART_rx.v:20.11-20.28" *)
  reg \M_RX_0.samplex16_counter[4] ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  wire \M_RX_0.samplex16_counter[4]_$_DFF_PN1__Q_D ;
  wire \M_RX_0.samplex16_counter[4]_$_DFF_PN1__Q_D_$_OR__Y_A ;
  wire \M_RX_0.samplex16_counter[4]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A ;
  wire \M_RX_0.samplex16_counter[4]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A_$_ANDNOT__Y_A ;
  wire \M_RX_0.samplex16_counter[4]_$_OR__B_1_A ;
  wire \M_RX_0.samplex16_counter[4]_$_OR__B_1_Y ;
  wire \M_RX_0.samplex16_counter[4]_$_OR__B_A ;
  wire \M_RX_0.samplex16_counter[4]_$_OR__B_Y ;
  wire \M_RX_0.samplex16_counter[4]_$_OR__B_Y_$_NAND__A_Y ;
  wire \M_RX_0.samplex16_counter[4]_$_OR__B_Y_$_NAND__A_Y_$_ORNOT__B_Y ;
  (* hdlname = "M_RX_0 shiftreg" *)
  (* src = "src/UART_rx.v:19.11-19.19" *)
  reg \M_RX_0.shiftreg[0] ;
  wire \M_RX_0.shiftreg[0]_$_XNOR__B_Y ;
  wire \M_RX_0.shiftreg[0]_$_XNOR__B_Y_$_XOR__B_Y ;
  (* hdlname = "M_RX_0 shiftreg" *)
  (* src = "src/UART_rx.v:19.11-19.19" *)
  reg \M_RX_0.shiftreg[1] ;
  (* hdlname = "M_RX_0 shiftreg" *)
  (* src = "src/UART_rx.v:19.11-19.19" *)
  reg \M_RX_0.shiftreg[2] ;
  wire \M_RX_0.shiftreg[2]_$_XNOR__B_Y ;
  (* hdlname = "M_RX_0 shiftreg" *)
  (* src = "src/UART_rx.v:19.11-19.19" *)
  reg \M_RX_0.shiftreg[3] ;
  (* hdlname = "M_RX_0 shiftreg" *)
  (* src = "src/UART_rx.v:19.11-19.19" *)
  reg \M_RX_0.shiftreg[4] ;
  wire \M_RX_0.shiftreg[4]_$_XOR__B_Y ;
  wire \M_RX_0.shiftreg[4]_$_XOR__B_Y_$_XOR__B_Y ;
  (* hdlname = "M_RX_0 shiftreg" *)
  (* src = "src/UART_rx.v:19.11-19.19" *)
  reg \M_RX_0.shiftreg[5] ;
  (* hdlname = "M_RX_0 shiftreg" *)
  (* src = "src/UART_rx.v:19.11-19.19" *)
  reg \M_RX_0.shiftreg[6] ;
  wire \M_RX_0.shiftreg[6]_$_XNOR__B_Y ;
  (* hdlname = "M_RX_0 shiftreg" *)
  (* src = "src/UART_rx.v:19.11-19.19" *)
  reg \M_RX_0.shiftreg[7] ;
  (* hdlname = "M_RX_0 state" *)
  (* src = "src/UART_rx.v:22.11-22.16" *)
  reg \M_RX_0.state[0] ;
  wire \M_RX_0.state[0]_$_NAND__A_Y ;
  wire \M_RX_0.state[0]_$_ORNOT__A_Y ;
  wire \M_RX_0.state[0]_$_ORNOT__A_Y_$_ANDNOT__B_Y ;
  (* hdlname = "M_RX_0 state" *)
  (* src = "src/UART_rx.v:22.11-22.16" *)
  reg \M_RX_0.state[1] ;
  (* hdlname = "M_RX_0 state" *)
  (* src = "src/UART_rx.v:22.11-22.16" *)
  reg \M_RX_0.state[2] ;
  wire \M_RX_0.state[2]_$_DFFE_PN0P__Q_E ;
  wire \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_A ;
  wire \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_A ;
  wire \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_A_$_ANDNOT__Y_A ;
  wire \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_A_$_ANDNOT__Y_B ;
  wire \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B ;
  wire \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__Y_A ;
  wire \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__Y_B ;
  wire \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B ;
  wire \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_OR__Y_A ;
  wire \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_OR__Y_B ;
  (* hdlname = "M_TX_0 TX_enable" *)
  (* src = "src/UART_tx.v:8.30-8.39" *)
  wire \M_TX_0.TX_enable ;
  (* hdlname = "M_TX_0 clkin" *)
  (* src = "src/UART_tx.v:8.16-8.21" *)
  wire \M_TX_0.clkin ;
  (* hdlname = "M_TX_0 count_tick" *)
  (* src = "src/UART_tx.v:18.11-18.21" *)
  reg \M_TX_0.count_tick[0]  = 1'h0;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  wire \M_TX_0.count_tick[0]_$_DFF_PN0__Q_D ;
  (* hdlname = "M_TX_0 count_tick" *)
  (* src = "src/UART_tx.v:18.11-18.21" *)
  reg \M_TX_0.count_tick[1]  = 1'h0;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  wire \M_TX_0.count_tick[1]_$_DFF_PN0__Q_D ;
  wire \M_TX_0.count_tick[1]_$_DFF_PN0__Q_D_$_NOR__Y_A ;
  wire \M_TX_0.count_tick[1]_$_NOR__B_Y ;
  wire \M_TX_0.count_tick[1]_$_ORNOT__A_Y ;
  (* hdlname = "M_TX_0 count_tick" *)
  (* src = "src/UART_tx.v:18.11-18.21" *)
  reg \M_TX_0.count_tick[2]  = 1'h1;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  wire \M_TX_0.count_tick[2]_$_DFF_PN1__Q_D ;
  wire \M_TX_0.count_tick[2]_$_DFF_PN1__Q_D_$_OR__Y_A ;
  (* hdlname = "M_TX_0 count_tick" *)
  (* src = "src/UART_tx.v:18.11-18.21" *)
  reg \M_TX_0.count_tick[3]  = 1'h0;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  wire \M_TX_0.count_tick[3]_$_DFF_PN0__Q_D ;
  wire \M_TX_0.count_tick[3]_$_DFF_PN0__Q_D_$_NOR__Y_A ;
  wire \M_TX_0.count_tick[3]_$_DFF_PN0__Q_D_$_NOR__Y_A_$_XNOR__Y_A ;
  wire \M_TX_0.count_tick[3]_$_NOR__A_Y ;
  wire \M_TX_0.count_tick[3]_$_OR__A_Y ;
  wire \M_TX_0.count_tick[3]_$_OR__A_Y_$_NOR__B_Y ;
  wire \M_TX_0.count_tick[3]_$_OR__A_Y_$_OR__B_Y ;
  wire \M_TX_0.count_tick[3]_$_OR__A_Y_$_OR__B_Y_$_OR__A_Y ;
  wire \M_TX_0.count_tick[3]_$_OR__A_Y_$_OR__B_Y_$_OR__A_Y_$_ANDNOT__B_Y ;
  (* hdlname = "M_TX_0 count_tick" *)
  (* src = "src/UART_tx.v:18.11-18.21" *)
  reg \M_TX_0.count_tick[4]  = 1'h0;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  wire \M_TX_0.count_tick[4]_$_DFF_PN0__Q_D ;
  wire \M_TX_0.count_tick[4]_$_DFF_PN0__Q_D_$_NOR__Y_A ;
  wire \M_TX_0.count_tick[4]_$_NOR__B_Y ;
  wire \M_TX_0.count_tick[4]_$_NOT__A_Y ;
  wire \M_TX_0.count_tick[4]_$_NOT__A_Y_$_ANDNOT__A_B ;
  wire \M_TX_0.count_tick[4]_$_NOT__A_Y_$_XOR__B_A ;
  (* hdlname = "M_TX_0 count_tick" *)
  (* src = "src/UART_tx.v:18.11-18.21" *)
  reg \M_TX_0.count_tick[5]  = 1'h1;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  wire \M_TX_0.count_tick[5]_$_DFF_PN1__Q_D ;
  wire \M_TX_0.count_tick[5]_$_XOR__B_A ;
  wire \M_TX_0.count_tick[5]_$_XOR__B_Y ;
  (* hdlname = "M_TX_0 count_tick" *)
  (* src = "src/UART_tx.v:18.11-18.21" *)
  reg \M_TX_0.count_tick[6]  = 1'h1;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  wire \M_TX_0.count_tick[6]_$_DFF_PN1__Q_D ;
  wire \M_TX_0.count_tick[6]_$_DFF_PN1__Q_D_$_OR__Y_A ;
  wire \M_TX_0.count_tick[6]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XNOR__Y_A ;
  wire \M_TX_0.count_tick[6]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XNOR__Y_A_$_ORNOT__Y_A ;
  (* hdlname = "M_TX_0 count_tick" *)
  (* src = "src/UART_tx.v:18.11-18.21" *)
  reg \M_TX_0.count_tick[7]  = 1'h0;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  wire \M_TX_0.count_tick[7]_$_DFF_PN0__Q_D ;
  wire \M_TX_0.count_tick[7]_$_DFF_PN0__Q_D_$_NOR__Y_A ;
  wire \M_TX_0.count_tick[7]_$_DFF_PN0__Q_D_$_NOR__Y_A_$_XOR__Y_A ;
  wire \M_TX_0.count_tick[7]_$_NOR__B_Y ;
  wire \M_TX_0.count_tick[7]_$_NOR__B_Y_$_NAND__B_Y ;
  wire \M_TX_0.count_tick[7]_$_OR__B_Y ;
  wire \M_TX_0.count_tick[7]_$_OR__B_Y_$_OR__B_A ;
  wire \M_TX_0.count_tick[7]_$_OR__B_Y_$_OR__B_Y ;
  (* hdlname = "M_TX_0 count_tick" *)
  (* src = "src/UART_tx.v:18.11-18.21" *)
  reg \M_TX_0.count_tick[8]  = 1'h1;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  wire \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D ;
  wire \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A ;
  wire \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A ;
  wire \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A_$_ANDNOT__B_Y ;
  wire \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A_$_ANDNOT__B_Y_$_OR__B_Y ;
  wire \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A_$_OR__Y_A ;
  wire \M_TX_0.count_tick[8]_$_NOT__A_Y ;
  (* hdlname = "M_TX_0 data_in" *)
  (* src = "src/UART_tx.v:7.22-7.29" *)
  wire \M_TX_0.data_in[0] ;
  (* hdlname = "M_TX_0 data_in" *)
  (* src = "src/UART_tx.v:7.22-7.29" *)
  wire \M_TX_0.data_in[1] ;
  (* hdlname = "M_TX_0 data_in" *)
  (* src = "src/UART_tx.v:7.22-7.29" *)
  wire \M_TX_0.data_in[2] ;
  (* hdlname = "M_TX_0 data_in" *)
  (* src = "src/UART_tx.v:7.22-7.29" *)
  wire \M_TX_0.data_in[3] ;
  (* hdlname = "M_TX_0 data_in" *)
  (* src = "src/UART_tx.v:7.22-7.29" *)
  wire \M_TX_0.data_in[4] ;
  (* hdlname = "M_TX_0 data_in" *)
  (* src = "src/UART_tx.v:7.22-7.29" *)
  wire \M_TX_0.data_in[5] ;
  (* hdlname = "M_TX_0 data_in" *)
  (* src = "src/UART_tx.v:7.22-7.29" *)
  wire \M_TX_0.data_in[6] ;
  (* hdlname = "M_TX_0 data_in" *)
  (* src = "src/UART_tx.v:7.22-7.29" *)
  wire \M_TX_0.data_in[7] ;
  (* hdlname = "M_TX_0 data_out" *)
  (* src = "src/UART_tx.v:9.16-9.24" *)
  wire \M_TX_0.data_out ;
  (* hdlname = "M_TX_0 datcount" *)
  (* src = "src/UART_tx.v:20.11-20.19" *)
  reg \M_TX_0.datcount[0]  = 1'h1;
  wire \M_TX_0.datcount[0]_$_DFFE_PN1P__Q_D ;
  (* hdlname = "M_TX_0 datcount" *)
  (* src = "src/UART_tx.v:20.11-20.19" *)
  reg \M_TX_0.datcount[1]  = 1'h1;
  wire \M_TX_0.datcount[1]_$_DFFE_PN1P__Q_D ;
  wire \M_TX_0.datcount[1]_$_DFFE_PN1P__Q_D_$_OR__Y_A ;
  (* hdlname = "M_TX_0 datcount" *)
  (* src = "src/UART_tx.v:20.11-20.19" *)
  reg \M_TX_0.datcount[2]  = 1'h1;
  wire \M_TX_0.datcount[2]_$_DFFE_PN1P__Q_D ;
  wire \M_TX_0.datcount[2]_$_DFFE_PN1P__Q_E ;
  wire \M_TX_0.datcount[2]_$_DFFE_PN1P__Q_E_$_AND__Y_A ;
  wire \M_TX_0.datcount[2]_$_DFFE_PN1P__Q_E_$_AND__Y_A_$_ANDNOT__B_Y ;
  wire \M_TX_0.datcount[2]_$_NOR__B_A ;
  wire \M_TX_0.datcount[2]_$_NOR__B_Y ;
  wire \M_TX_0.datcount[2]_$_XOR__B_A ;
  wire \M_TX_0.datcount[2]_$_XOR__B_Y ;
  (* hdlname = "M_TX_0 nextstate" *)
  (* src = "src/UART_tx.v:22.18-22.27" *)
  wire \M_TX_0.nextstate[0] ;
  wire \M_TX_0.nextstate[0]_$_MUX__Y_A ;
  wire \M_TX_0.nextstate[0]_$_MUX__Y_A_$_ORNOT__Y_A ;
  (* hdlname = "M_TX_0 nextstate" *)
  (* src = "src/UART_tx.v:22.18-22.27" *)
  wire \M_TX_0.nextstate[1] ;
  wire \M_TX_0.nextstate[1]_$_ANDNOT__Y_A ;
  wire \M_TX_0.nextstate[1]_$_ANDNOT__Y_A_$_ORNOT__Y_A ;
  (* hdlname = "M_TX_0 nextstate" *)
  (* src = "src/UART_tx.v:22.18-22.27" *)
  wire \M_TX_0.nextstate[2] ;
  wire \M_TX_0.nextstate[2]_$_ANDNOT__Y_A ;
  (* hdlname = "M_TX_0 parity_bit" *)
  (* src = "src/UART_tx.v:24.16-24.26" *)
  reg \M_TX_0.parity_bit ;
  wire \M_TX_0.parity_bit_$_AND__B_Y ;
  (* src = "src/UART_tx.v:48.27-48.35" *)
  wire \M_TX_0.parity_bit_$_DFFE_PP__Q_D ;
  wire \M_TX_0.parity_bit_$_DFFE_PP__Q_D_$_XOR__Y_A ;
  wire \M_TX_0.parity_bit_$_DFFE_PP__Q_D_$_XOR__Y_B ;
  wire \M_TX_0.parity_bit_$_DFFE_PP__Q_E ;
  wire \M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A ;
  wire \M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B ;
  wire \M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__B_A ;
  wire \M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__B_Y ;
  wire \M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__B_Y_$_ANDNOT__B_A ;
  wire \M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__B_Y_$_ANDNOT__B_A_$_ANDNOT__Y_B ;
  wire \M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__B_Y_$_ANDNOT__B_Y ;
  (* hdlname = "M_TX_0 reset" *)
  (* src = "src/UART_tx.v:8.23-8.28" *)
  wire \M_TX_0.reset ;
  (* hdlname = "M_TX_0 shiftreg" *)
  (* src = "src/UART_tx.v:19.11-19.19" *)
  reg \M_TX_0.shiftreg[0] ;
  wire \M_TX_0.shiftreg[0]_$_AND__B_Y ;
  (* hdlname = "M_TX_0 shiftreg" *)
  (* src = "src/UART_tx.v:19.11-19.19" *)
  reg \M_TX_0.shiftreg[1] ;
  (* hdlname = "M_TX_0 shiftreg" *)
  (* src = "src/UART_tx.v:19.11-19.19" *)
  reg \M_TX_0.shiftreg[2] ;
  (* hdlname = "M_TX_0 shiftreg" *)
  (* src = "src/UART_tx.v:19.11-19.19" *)
  reg \M_TX_0.shiftreg[3] ;
  (* hdlname = "M_TX_0 shiftreg" *)
  (* src = "src/UART_tx.v:19.11-19.19" *)
  reg \M_TX_0.shiftreg[4] ;
  (* hdlname = "M_TX_0 shiftreg" *)
  (* src = "src/UART_tx.v:19.11-19.19" *)
  reg \M_TX_0.shiftreg[5] ;
  (* hdlname = "M_TX_0 shiftreg" *)
  (* src = "src/UART_tx.v:19.11-19.19" *)
  reg \M_TX_0.shiftreg[6] ;
  (* hdlname = "M_TX_0 shiftreg" *)
  (* src = "src/UART_tx.v:19.11-19.19" *)
  reg \M_TX_0.shiftreg[7] ;
  (* hdlname = "M_TX_0 shiftregnext" *)
  (* src = "src/UART_tx.v:19.21-19.33" *)
  wire \M_TX_0.shiftregnext[0] ;
  (* hdlname = "M_TX_0 shiftregnext" *)
  (* src = "src/UART_tx.v:19.21-19.33" *)
  wire \M_TX_0.shiftregnext[1] ;
  (* hdlname = "M_TX_0 shiftregnext" *)
  (* src = "src/UART_tx.v:19.21-19.33" *)
  wire \M_TX_0.shiftregnext[2] ;
  (* hdlname = "M_TX_0 shiftregnext" *)
  (* src = "src/UART_tx.v:19.21-19.33" *)
  wire \M_TX_0.shiftregnext[3] ;
  (* hdlname = "M_TX_0 shiftregnext" *)
  (* src = "src/UART_tx.v:19.21-19.33" *)
  wire \M_TX_0.shiftregnext[4] ;
  (* hdlname = "M_TX_0 shiftregnext" *)
  (* src = "src/UART_tx.v:19.21-19.33" *)
  wire \M_TX_0.shiftregnext[5] ;
  (* hdlname = "M_TX_0 shiftregnext" *)
  (* src = "src/UART_tx.v:19.21-19.33" *)
  wire \M_TX_0.shiftregnext[6] ;
  (* hdlname = "M_TX_0 shiftregnext" *)
  (* src = "src/UART_tx.v:19.21-19.33" *)
  wire \M_TX_0.shiftregnext[7] ;
  (* hdlname = "M_TX_0 state" *)
  (* src = "src/UART_tx.v:22.11-22.16" *)
  reg \M_TX_0.state[0] ;
  wire \M_TX_0.state[0]_$_DFFE_PN0P__Q_E ;
  wire \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B ;
  wire \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A ;
  wire \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_A ;
  wire \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_A_$_MUX__Y_A ;
  wire \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_A_$_MUX__Y_A_$_OR__A_Y ;
  wire \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_B ;
  wire \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__Y_A ;
  wire \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__Y_A_$_ANDNOT__Y_B ;
  wire \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B ;
  wire \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_A ;
  wire \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_B ;
  wire \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y ;
  wire \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_B ;
  wire \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__B_Y ;
  (* hdlname = "M_TX_0 state" *)
  (* src = "src/UART_tx.v:22.11-22.16" *)
  reg \M_TX_0.state[1] ;
  (* hdlname = "M_TX_0 state" *)
  (* src = "src/UART_tx.v:22.11-22.16" *)
  reg \M_TX_0.state[2] ;
  wire \data_tx[0]_$_XOR__B_Y ;
  wire \data_tx[2]_$_XNOR__B_Y ;
  wire \data_tx[4]_$_XOR__B_Y ;
  wire \data_tx[6]_$_XNOR__B_Y ;
  wire \error_flag_$_NOT__Y_A ;
  wire \error_flag_$_NOT__Y_A_$_ANDNOT__A_Y ;
  wire \error_flag_$_NOT__Y_A_$_ANDNOT__A_Y_$_ANDNOT__A_B ;
  wire \error_flag_$_NOT__Y_A_$_ANDNOT__A_Y_$_ANDNOT__A_Y ;
  wire \error_flag_$_NOT__Y_A_$_ANDNOT__A_Y_$_ANDNOT__A_Y_$_ANDNOT__A_B ;
  wire \error_flag_$_NOT__Y_A_$_ANDNOT__A_Y_$_ANDNOT__A_Y_$_ANDNOT__A_Y ;
  wire \error_flag_$_NOT__Y_A_$_OR__Y_A ;
  wire \error_flag_$_NOT__Y_A_$_OR__Y_A_$_ANDNOT__B_Y ;
  wire \error_flag_$_NOT__Y_A_$_OR__Y_B ;
  wire \parity_err_$_ANDNOT__Y_B ;
  wire \parity_err_$_ANDNOT__Y_B_$_OR__Y_A ;
  wire \parity_err_$_ANDNOT__Y_B_$_OR__Y_A_$_XOR__Y_A ;
  wire \rx_done_$_NOT__Y_A ;
  wire \rx_done_$_NOT__Y_A_$_ANDNOT__B_Y ;
  wire \rx_done_$_NOT__Y_A_$_OR__Y_A ;
  wire \rx_done_$_NOT__Y_A_$_OR__Y_B ;
  wire \rx_done_$_NOT__Y_A_$_OR__Y_B_$_ORNOT__B_A ;
  wire \rx_done_$_NOT__Y_A_$_OR__Y_B_$_ORNOT__B_Y ;
  wire \rx_done_$_NOT__Y_A_$_OR__Y_B_$_ORNOT__B_Y_$_NOR__A_Y ;
  wire \tx_$_OR__Y_A ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.data_counter[0]  <= 1'h1;
    else if (\M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y ) \M_RX_0.data_counter[0]  <= \M_RX_0.data_counter[0]_$_DFFE_PN1P__Q_D ;
  assign \M_RX_0.data_counter[0]_$_DFFE_PN1P__Q_D  = \M_RX_0.data_counter[3]_$_OR__A_Y_$_MUX__S_Y  | ~(\M_RX_0.data_counter[0] );
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.data_counter[1]  <= 1'h1;
    else if (\M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y ) \M_RX_0.data_counter[1]  <= \M_RX_0.data_counter[1]_$_DFFE_PN1P__Q_D ;
  assign \M_RX_0.data_counter[1]_$_DFFE_PN1P__Q_D  = \M_RX_0.data_counter[1]_$_XNOR__A_Y  | \M_RX_0.data_counter[3]_$_OR__A_Y_$_MUX__S_Y ;
  assign \M_RX_0.data_counter[1]_$_NOR__A_Y  = ~(\M_RX_0.data_counter[1]  | \M_RX_0.data_counter[0] );
  assign \M_RX_0.data_counter[1]_$_XNOR__A_Y  = ~(\M_RX_0.data_counter[1]  ^ \M_RX_0.data_counter[0] );
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.data_counter[2]  <= 1'h1;
    else if (\M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y ) \M_RX_0.data_counter[2]  <= \M_RX_0.data_counter[2]_$_DFFE_PN1P__Q_D ;
  assign \M_RX_0.data_counter[2]_$_DFFE_PN1P__Q_D  = \M_RX_0.data_counter[2]_$_DFFE_PN1P__Q_D_$_OR__Y_A  | \M_RX_0.data_counter[3]_$_OR__A_Y_$_MUX__S_Y ;
  assign \M_RX_0.data_counter[2]_$_DFFE_PN1P__Q_D_$_OR__Y_A  = \M_RX_0.data_counter[1]_$_NOR__A_Y  ^ \M_RX_0.data_counter[2] ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.data_counter[3]  <= 1'h0;
    else if (\M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y ) \M_RX_0.data_counter[3]  <= \M_RX_0.data_counter[3]_$_DFFE_PN0P__Q_D ;
  assign \M_RX_0.data_counter[3]_$_DFFE_PN0P__Q_D  = \M_RX_0.data_counter[3]_$_DFFE_PN0P__Q_D_$_ANDNOT__Y_A  & ~(\M_RX_0.data_counter[3]_$_OR__A_Y_$_MUX__S_Y );
  assign \M_RX_0.data_counter[3]_$_DFFE_PN0P__Q_D_$_ANDNOT__Y_A  = \M_RX_0.data_counter[3]_$_DFFE_PN0P__Q_D_$_ANDNOT__Y_A_$_XOR__Y_A  ^ \M_RX_0.data_counter[3] ;
  assign \M_RX_0.data_counter[3]_$_DFFE_PN0P__Q_D_$_ANDNOT__Y_A_$_XOR__Y_A  = \M_RX_0.data_counter[1]_$_NOR__A_Y  & ~(\M_RX_0.data_counter[2] );
  assign \M_RX_0.data_counter[3]_$_NOR__A_Y  = ~(\M_RX_0.data_counter[3]  | \M_RX_0.data_counter[2] );
  assign \M_RX_0.data_counter[3]_$_OR__A_Y  = \M_RX_0.data_counter[3]  | \M_RX_0.data_counter[2] ;
  assign \M_RX_0.data_counter[3]_$_OR__A_Y_$_MUX__S_Y  = \M_RX_0.data_counter[3]_$_OR__A_Y  ? \M_RX_0.data_counter[3]_$_NOR__A_Y  : \M_RX_0.data_counter[1]_$_NOR__A_Y ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.data_out[0]  <= 1'h0;
    else if (\rx_done_$_NOT__Y_A_$_ANDNOT__B_Y ) \M_RX_0.data_out[0]  <= \M_RX_0.shiftreg[0] ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.data_out[1]  <= 1'h0;
    else if (\rx_done_$_NOT__Y_A_$_ANDNOT__B_Y ) \M_RX_0.data_out[1]  <= \M_RX_0.shiftreg[1] ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.data_out[2]  <= 1'h0;
    else if (\rx_done_$_NOT__Y_A_$_ANDNOT__B_Y ) \M_RX_0.data_out[2]  <= \M_RX_0.shiftreg[2] ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.data_out[3]  <= 1'h0;
    else if (\rx_done_$_NOT__Y_A_$_ANDNOT__B_Y ) \M_RX_0.data_out[3]  <= \M_RX_0.shiftreg[3] ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.data_out[4]  <= 1'h0;
    else if (\rx_done_$_NOT__Y_A_$_ANDNOT__B_Y ) \M_RX_0.data_out[4]  <= \M_RX_0.shiftreg[4] ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.data_out[5]  <= 1'h0;
    else if (\rx_done_$_NOT__Y_A_$_ANDNOT__B_Y ) \M_RX_0.data_out[5]  <= \M_RX_0.shiftreg[5] ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.data_out[6]  <= 1'h0;
    else if (\rx_done_$_NOT__Y_A_$_ANDNOT__B_Y ) \M_RX_0.data_out[6]  <= \M_RX_0.shiftreg[6] ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.data_out[7]  <= 1'h0;
    else if (\rx_done_$_NOT__Y_A_$_ANDNOT__B_Y ) \M_RX_0.data_out[7]  <= \M_RX_0.shiftreg[7] ;
  assign \M_RX_0.nextstate[0]  = \M_RX_0.nextstate[1]_$_ORNOT__Y_B  & ~(\M_RX_0.nextstate[0]_$_ANDNOT__Y_B );
  assign \M_RX_0.nextstate[0]_$_ANDNOT__Y_B  = \M_RX_0.nextstate[0]_$_ANDNOT__Y_B_$_ANDNOT__Y_A  & ~(\M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_A );
  assign \M_RX_0.nextstate[0]_$_ANDNOT__Y_B_$_ANDNOT__Y_A  = \M_RX_0.nextstate[2]_$_ANDNOT__Y_B_$_ANDNOT__Y_A  & ~(\M_RX_0.nextstate[0]_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_B );
  assign \M_RX_0.nextstate[1]  = \M_RX_0.nextstate[1]_$_ORNOT__Y_A  | ~(\M_RX_0.nextstate[1]_$_ORNOT__Y_B );
  assign \M_RX_0.nextstate[1]_$_ORNOT__Y_A  = \M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_A  | \M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B ;
  assign \M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_A  = \M_RX_0.state[0]_$_ORNOT__A_Y_$_ANDNOT__B_Y  & ~(\M_RX_0.sample_counter[1]_$_OR__A_Y_$_OR__A_Y_$_OR__A_Y );
  assign \M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B  = \M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B_$_ANDNOT__Y_A  & ~(\M_RX_0.data_counter[3]_$_OR__A_Y_$_MUX__S_Y );
  assign \M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y  = \M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B_$_ANDNOT__Y_A  & ~(\M_RX_0.samplex16_counter[4]_$_OR__B_Y_$_NAND__A_Y_$_ORNOT__B_Y );
  assign \M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B_$_ANDNOT__Y_A  = \error_flag_$_NOT__Y_A_$_OR__Y_B  & ~(\M_RX_0.state[0]_$_NAND__A_Y );
  assign \M_RX_0.nextstate[0]_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_B  = \M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B  | \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_A_$_OR__Y_A_$_ANDNOT__B_Y ;
  assign \M_RX_0.nextstate[1]_$_ORNOT__Y_B  = \M_RX_0.nextstate[1]_$_ORNOT__Y_B_$_OR__Y_A  | \M_RX_0.state[0]_$_ORNOT__A_Y_$_ANDNOT__B_Y ;
  assign \M_RX_0.nextstate[1]_$_ORNOT__Y_B_$_OR__Y_A  = \M_RX_0.state[2]  ? \M_RX_0.nextstate[1]_$_ORNOT__Y_B_$_OR__Y_A_$_MUX__Y_B  : \M_RX_0.state[0] ;
  assign \M_RX_0.nextstate[1]_$_ORNOT__Y_B_$_OR__Y_A_$_MUX__Y_B  = ~\M_RX_0.state[1] ;
  assign \M_RX_0.nextstate[2]  = \M_RX_0.nextstate[1]_$_ORNOT__Y_B  & ~(\M_RX_0.nextstate[2]_$_ANDNOT__Y_B );
  assign \M_RX_0.nextstate[2]_$_ANDNOT__Y_B  = \M_RX_0.nextstate[2]_$_ANDNOT__Y_B_$_ANDNOT__Y_A  & ~(\M_RX_0.nextstate[2]_$_ANDNOT__Y_B_$_ANDNOT__Y_B );
  assign \M_RX_0.nextstate[2]_$_ANDNOT__Y_B_$_ANDNOT__Y_A  = \M_RX_0.rx  | ~(\error_flag_$_NOT__Y_A_$_OR__Y_A_$_ANDNOT__B_Y );
  assign \M_RX_0.nextstate[2]_$_ANDNOT__Y_B_$_ANDNOT__Y_B  = \M_RX_0.data_counter[3]_$_OR__A_Y_$_MUX__S_Y  & \M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B_$_ANDNOT__Y_A ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.rx  <= 1'h0;
    else if (\M_RX_0.samplex16_counter[4]_$_OR__B_Y_$_NAND__A_Y ) \M_RX_0.rx  <= rx;
  assign \M_RX_0.rx_prev_$_ANDNOT__A_Y  = \M_RX_0.rx_prev  & ~(\M_RX_0.rx );
  assign \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_Y  = ~(\M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_A  | \M_RX_0.rx_prev_$_ANDNOT__A_Y );
  assign \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_A_$_ANDNOT__A_Y  = \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_A  & ~(\M_RX_0.state[0]_$_ORNOT__A_Y_$_ANDNOT__B_Y );
  assign \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_A_$_ANDNOT__A_Y_$_ANDNOT__A_Y  = \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_A_$_ANDNOT__A_Y  & ~(\rx_done_$_NOT__Y_A_$_OR__Y_B_$_ORNOT__B_Y );
  assign \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_A  = \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_A_$_OR__Y_A  | \M_RX_0.state[2] ;
  assign \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_A_$_OR__Y_A_$_ANDNOT__B_Y  = \M_RX_0.state[2]  & ~(\M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_A_$_OR__Y_A );
  assign \rx_done_$_NOT__Y_A_$_OR__Y_B_$_ORNOT__B_A  = \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_A_$_OR__Y_A_$_ANDNOT__B_Y  | \M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B_$_ANDNOT__Y_A ;
  assign \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_A_$_OR__Y_A  = \M_RX_0.state[0]  | \M_RX_0.state[1] ;
  assign \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_Y_$_ANDNOT__B_Y  = \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_Y_$_ANDNOT__B_A  & ~(\M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_Y );
  assign \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_Y_$_ANDNOT__B_A  = \M_RX_0.sample_counter[1]_$_OR__A_Y_$_MUX__A_Y  | ~(\error_flag_$_NOT__Y_A_$_OR__Y_A_$_ANDNOT__B_Y );
  assign \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_Y_$_ANDNOT__B_Y_$_ANDNOT__A_Y  = \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_Y_$_ANDNOT__B_Y  & ~(\M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_Y_$_ANDNOT__B_Y_$_ANDNOT__A_B );
  assign \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_Y_$_ANDNOT__B_Y_$_ANDNOT__A_B  = \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_A_$_ANDNOT__A_Y_$_ANDNOT__A_Y  | ~(\M_RX_0.samplex16_counter[4]_$_OR__B_Y_$_NAND__A_Y );
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.rx_prev  <= 1'h0;
    else if (\M_RX_0.samplex16_counter[4]_$_OR__B_Y_$_NAND__A_Y ) \M_RX_0.rx_prev  <= \M_RX_0.rx ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.sample_counter[0]  <= 1'h1;
    else if (\M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_Y_$_ANDNOT__B_Y_$_ANDNOT__A_Y ) \M_RX_0.sample_counter[0]  <= \M_RX_0.sample_counter_next[0] ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.sample_counter[1]  <= 1'h1;
    else if (\M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_Y_$_ANDNOT__B_Y_$_ANDNOT__A_Y ) \M_RX_0.sample_counter[1]  <= \M_RX_0.sample_counter_next[1] ;
  assign \M_RX_0.sample_counter[3]_$_XNOR__B_A_$_ANDNOT__Y_A  = ~(\M_RX_0.sample_counter[1]  | \M_RX_0.sample_counter[0] );
  assign \M_RX_0.sample_counter[1]_$_OR__A_Y  = \M_RX_0.sample_counter[1]  | \M_RX_0.sample_counter[0] ;
  assign \M_RX_0.sample_counter[1]_$_OR__A_Y_$_MUX__A_Y  = \M_RX_0.sample_counter[3]_$_OR__B_Y  ? \M_RX_0.sample_counter[3]_$_OR__B_Y  : \M_RX_0.sample_counter[1]_$_OR__A_Y ;
  assign \M_RX_0.sample_counter[1]_$_OR__A_Y_$_OR__A_Y  = \M_RX_0.sample_counter[1]_$_OR__A_Y  | \M_RX_0.sample_counter[3]_$_OR__B_Y ;
  assign \M_RX_0.sample_counter[1]_$_OR__A_Y_$_OR__A_Y_$_OR__A_Y  = \M_RX_0.sample_counter[1]_$_OR__A_Y_$_OR__A_Y  | \M_RX_0.rx ;
  assign \M_RX_0.sample_counter[1]_$_XOR__A_Y  = \M_RX_0.sample_counter[1]  ^ \M_RX_0.sample_counter[0] ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.sample_counter[2]  <= 1'h1;
    else if (\M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_Y_$_ANDNOT__B_Y_$_ANDNOT__A_Y ) \M_RX_0.sample_counter[2]  <= \M_RX_0.sample_counter_next[2] ;
  assign \M_RX_0.sample_counter[2]_$_XNOR__B_Y  = ~(\M_RX_0.sample_counter[3]_$_XNOR__B_A_$_ANDNOT__Y_A  ^ \M_RX_0.sample_counter[2] );
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.sample_counter[3]  <= 1'h0;
    else if (\M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_Y_$_ANDNOT__B_Y_$_ANDNOT__A_Y ) \M_RX_0.sample_counter[3]  <= \M_RX_0.sample_counter_next[3] ;
  assign \M_RX_0.sample_counter[3]_$_OR__B_Y  = \M_RX_0.sample_counter[2]  | \M_RX_0.sample_counter[3] ;
  assign \M_RX_0.sample_counter[3]_$_XNOR__B_Y  = ~(\M_RX_0.sample_counter[3]_$_XNOR__B_A  ^ \M_RX_0.sample_counter[3] );
  assign \M_RX_0.sample_counter[3]_$_XNOR__B_A  = \M_RX_0.sample_counter[3]_$_XNOR__B_A_$_ANDNOT__Y_A  & ~(\M_RX_0.sample_counter[2] );
  assign \M_RX_0.sample_counter_next[0]  = \M_RX_0.sample_counter_next[0]_$_OR__Y_A  | \rx_done_$_NOT__Y_A_$_OR__Y_B_$_ORNOT__B_Y_$_NOR__A_Y ;
  assign \M_RX_0.sample_counter_next[0]_$_OR__Y_A  = \M_RX_0.sample_counter_next[0]_$_OR__Y_A_$_OR__Y_A  | \M_RX_0.sample_counter_next[0]_$_OR__Y_A_$_OR__Y_B ;
  assign \M_RX_0.sample_counter_next[0]_$_OR__Y_A_$_OR__Y_A  = \M_RX_0.state[0]_$_ORNOT__A_Y_$_ANDNOT__B_Y  & ~(\M_RX_0.sample_counter_next[0]_$_OR__Y_A_$_OR__Y_A_$_ANDNOT__Y_B );
  assign \M_RX_0.sample_counter_next[0]_$_OR__Y_A_$_OR__Y_A_$_ANDNOT__Y_B  = \M_RX_0.sample_counter[1]_$_OR__A_Y_$_MUX__A_Y  ? \M_RX_0.sample_counter[0]  : \M_RX_0.sample_counter[1]_$_OR__A_Y_$_OR__A_Y_$_OR__A_Y ;
  assign \M_RX_0.sample_counter_next[0]_$_OR__Y_A_$_OR__Y_B  = \M_RX_0.sample_counter_next[0]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_A  | \M_RX_0.sample_counter_next[0]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_B ;
  assign \M_RX_0.sample_counter_next[0]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_A  = \rx_done_$_NOT__Y_A_$_OR__Y_B_$_ORNOT__B_A  & ~(\M_RX_0.sample_counter_next[0]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_A_$_ANDNOT__Y_B );
  assign \M_RX_0.sample_counter_next[0]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_A_$_ANDNOT__Y_B  = \M_RX_0.sample_counter[1]_$_OR__A_Y_$_MUX__A_Y  & \M_RX_0.sample_counter[0] ;
  assign \M_RX_0.sample_counter_next[0]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_B  = \error_flag_$_NOT__Y_A_$_OR__Y_A_$_ANDNOT__B_Y  & ~(\M_RX_0.sample_counter[0] );
  assign \M_RX_0.sample_counter_next[1]  = \M_RX_0.sample_counter_next[1]_$_OR__Y_A  | \rx_done_$_NOT__Y_A_$_OR__Y_B_$_ORNOT__B_Y_$_NOR__A_Y ;
  assign \M_RX_0.sample_counter_next[1]_$_OR__Y_A  = \M_RX_0.sample_counter_next[1]_$_OR__Y_A_$_OR__Y_A  | \M_RX_0.sample_counter_next[1]_$_OR__Y_A_$_OR__Y_B ;
  assign \M_RX_0.sample_counter_next[1]_$_OR__Y_A_$_OR__Y_A  = \M_RX_0.state[0]_$_ORNOT__A_Y_$_ANDNOT__B_Y  & ~(\M_RX_0.sample_counter_next[1]_$_OR__Y_A_$_OR__Y_A_$_ANDNOT__Y_B );
  assign \M_RX_0.sample_counter_next[1]_$_OR__Y_A_$_OR__Y_A_$_ANDNOT__Y_B  = \M_RX_0.sample_counter[1]_$_OR__A_Y_$_MUX__A_Y  ? \M_RX_0.sample_counter[1]_$_XOR__A_Y  : \M_RX_0.sample_counter[1]_$_OR__A_Y_$_OR__A_Y_$_OR__A_Y ;
  assign \M_RX_0.sample_counter_next[1]_$_OR__Y_A_$_OR__Y_B  = \M_RX_0.sample_counter_next[1]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_A  | \M_RX_0.sample_counter_next[1]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_B ;
  assign \M_RX_0.sample_counter_next[1]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_A  = \rx_done_$_NOT__Y_A_$_OR__Y_B_$_ORNOT__B_A  & ~(\M_RX_0.sample_counter_next[1]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_A_$_ANDNOT__Y_B );
  assign \M_RX_0.sample_counter_next[1]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_A_$_ANDNOT__Y_B  = \M_RX_0.sample_counter[1]_$_XOR__A_Y  & \M_RX_0.sample_counter[1]_$_OR__A_Y_$_MUX__A_Y ;
  assign \M_RX_0.sample_counter_next[1]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_B  = \error_flag_$_NOT__Y_A_$_OR__Y_A_$_ANDNOT__B_Y  & ~(\M_RX_0.sample_counter[1]_$_XOR__A_Y );
  assign \M_RX_0.sample_counter_next[2]  = \M_RX_0.sample_counter_next[2]_$_OR__Y_A  | \rx_done_$_NOT__Y_A_$_OR__Y_B_$_ORNOT__B_Y_$_NOR__A_Y ;
  assign \M_RX_0.sample_counter_next[2]_$_OR__Y_A  = \M_RX_0.sample_counter_next[2]_$_OR__Y_A_$_OR__Y_A  | \M_RX_0.sample_counter_next[2]_$_OR__Y_A_$_OR__Y_B ;
  assign \M_RX_0.sample_counter_next[2]_$_OR__Y_A_$_OR__Y_A  = \M_RX_0.state[0]_$_ORNOT__A_Y_$_ANDNOT__B_Y  & ~(\M_RX_0.sample_counter_next[2]_$_OR__Y_A_$_OR__Y_A_$_ANDNOT__Y_B );
  assign \M_RX_0.sample_counter_next[2]_$_OR__Y_A_$_OR__Y_A_$_ANDNOT__Y_B  = \M_RX_0.sample_counter[1]_$_OR__A_Y_$_MUX__A_Y  ? \M_RX_0.sample_counter[2]_$_XNOR__B_Y  : \M_RX_0.sample_counter[1]_$_OR__A_Y_$_OR__A_Y_$_OR__A_Y ;
  assign \M_RX_0.sample_counter_next[2]_$_OR__Y_A_$_OR__Y_B  = \M_RX_0.sample_counter_next[2]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_A  | \M_RX_0.sample_counter_next[2]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_B ;
  assign \M_RX_0.sample_counter_next[2]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_A  = \rx_done_$_NOT__Y_A_$_OR__Y_B_$_ORNOT__B_A  & ~(\M_RX_0.sample_counter_next[2]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_A_$_ANDNOT__Y_B );
  assign \M_RX_0.sample_counter_next[2]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_A_$_ANDNOT__Y_B  = \M_RX_0.sample_counter[2]_$_XNOR__B_Y  & \M_RX_0.sample_counter[1]_$_OR__A_Y_$_MUX__A_Y ;
  assign \M_RX_0.sample_counter_next[2]_$_OR__Y_A_$_OR__Y_B_$_OR__Y_B  = \error_flag_$_NOT__Y_A_$_OR__Y_A_$_ANDNOT__B_Y  & ~(\M_RX_0.sample_counter[2]_$_XNOR__B_Y );
  assign \M_RX_0.sample_counter_next[3]  = ~(\M_RX_0.sample_counter_next[3]_$_NOR__Y_A  | \rx_done_$_NOT__Y_A_$_OR__Y_B_$_ORNOT__B_Y_$_NOR__A_Y );
  assign \M_RX_0.sample_counter_next[3]_$_NOR__Y_A  = \M_RX_0.sample_counter_next[3]_$_NOR__Y_A_$_ANDNOT__Y_A  & ~(\M_RX_0.sample_counter_next[3]_$_NOR__Y_A_$_ANDNOT__Y_B );
  assign \M_RX_0.sample_counter_next[3]_$_NOR__Y_A_$_ANDNOT__Y_A  = \M_RX_0.sample_counter_next[3]_$_NOR__Y_A_$_ANDNOT__Y_A_$_ANDNOT__Y_A  & ~(\M_RX_0.sample_counter_next[3]_$_NOR__Y_A_$_ANDNOT__Y_A_$_ANDNOT__Y_B );
  assign \M_RX_0.sample_counter_next[3]_$_NOR__Y_A_$_ANDNOT__Y_A_$_ANDNOT__Y_B  = \rx_done_$_NOT__Y_A_$_OR__Y_B_$_ORNOT__B_A  & ~(\M_RX_0.sample_counter_next[3]_$_NOR__Y_A_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_ANDNOT__Y_B );
  assign \M_RX_0.sample_counter_next[3]_$_NOR__Y_A_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_ANDNOT__Y_B  = \M_RX_0.sample_counter[3]_$_XNOR__B_Y  & \M_RX_0.sample_counter[1]_$_OR__A_Y_$_MUX__A_Y ;
  assign \M_RX_0.sample_counter_next[3]_$_NOR__Y_A_$_ANDNOT__Y_B  = \M_RX_0.state[0]_$_ORNOT__A_Y_$_ANDNOT__B_Y  & ~(\M_RX_0.sample_counter_next[3]_$_NOR__Y_A_$_ANDNOT__Y_B_$_ANDNOT__Y_B );
  assign \M_RX_0.sample_counter_next[3]_$_NOR__Y_A_$_ANDNOT__Y_B_$_ANDNOT__Y_B  = \M_RX_0.sample_counter[1]_$_OR__A_Y_$_MUX__A_Y  ? \M_RX_0.sample_counter[3]_$_XNOR__B_Y  : \M_RX_0.sample_counter[1]_$_OR__A_Y_$_OR__A_Y_$_OR__A_Y ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.samplex16_counter[0]  <= 1'h0;
    else \M_RX_0.samplex16_counter[0]  <= \M_RX_0.samplex16_counter[0]_$_DFF_PN0__Q_D ;
  assign \M_RX_0.samplex16_counter[0]_$_DFF_PN0__Q_D  = ~(\M_RX_0.samplex16_counter[4]_$_OR__B_Y_$_NAND__A_Y  | \M_RX_0.samplex16_counter[0] );
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.samplex16_counter[1]  <= 1'h1;
    else \M_RX_0.samplex16_counter[1]  <= \M_RX_0.samplex16_counter[1]_$_DFF_PN1__Q_D ;
  assign \M_RX_0.samplex16_counter[1]_$_DFF_PN1__Q_D  = \M_RX_0.samplex16_counter[1]_$_XNOR__A_Y  | \M_RX_0.samplex16_counter[4]_$_OR__B_Y_$_NAND__A_Y ;
  assign \M_RX_0.samplex16_counter[1]_$_NOR__A_Y  = ~(\M_RX_0.samplex16_counter[1]  | \M_RX_0.samplex16_counter[0] );
  assign \M_RX_0.samplex16_counter[1]_$_XNOR__A_Y  = ~(\M_RX_0.samplex16_counter[1]  ^ \M_RX_0.samplex16_counter[0] );
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.samplex16_counter[2]  <= 1'h1;
    else \M_RX_0.samplex16_counter[2]  <= \M_RX_0.samplex16_counter[2]_$_DFF_PN1__Q_D ;
  assign \M_RX_0.samplex16_counter[2]_$_DFF_PN1__Q_D  = \M_RX_0.samplex16_counter[2]_$_DFF_PN1__Q_D_$_OR__Y_A  | \M_RX_0.samplex16_counter[4]_$_OR__B_Y_$_NAND__A_Y ;
  assign \M_RX_0.samplex16_counter[2]_$_DFF_PN1__Q_D_$_OR__Y_A  = \M_RX_0.samplex16_counter[1]_$_NOR__A_Y  ^ \M_RX_0.samplex16_counter[2] ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.samplex16_counter[3]  <= 1'h0;
    else \M_RX_0.samplex16_counter[3]  <= \M_RX_0.samplex16_counter[3]_$_DFF_PN0__Q_D ;
  assign \M_RX_0.samplex16_counter[3]_$_DFF_PN0__Q_D  = ~(\M_RX_0.samplex16_counter[3]_$_DFF_PN0__Q_D_$_NOR__Y_A  | \M_RX_0.samplex16_counter[4]_$_OR__B_Y_$_NAND__A_Y );
  assign \M_RX_0.samplex16_counter[3]_$_DFF_PN0__Q_D_$_NOR__Y_A  = ~(\M_RX_0.samplex16_counter[3]_$_DFF_PN0__Q_D_$_NOR__Y_A_$_XNOR__Y_A  ^ \M_RX_0.samplex16_counter[3] );
  assign \M_RX_0.samplex16_counter[3]_$_DFF_PN0__Q_D_$_NOR__Y_A_$_XNOR__Y_A  = \M_RX_0.samplex16_counter[1]_$_NOR__A_Y  & ~(\M_RX_0.samplex16_counter[2] );
  assign \M_RX_0.samplex16_counter[3]_$_NOR__B_Y  = ~(\M_RX_0.samplex16_counter[2]  | \M_RX_0.samplex16_counter[3] );
  assign \M_RX_0.samplex16_counter[3]_$_OR__B_Y  = \M_RX_0.samplex16_counter[2]  | \M_RX_0.samplex16_counter[3] ;
  assign \M_RX_0.samplex16_counter[4]_$_OR__B_1_A  = \M_RX_0.samplex16_counter[3]_$_NOR__B_Y  | \M_RX_0.samplex16_counter[3]_$_OR__B_Y ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.samplex16_counter[4]  <= 1'h1;
    else \M_RX_0.samplex16_counter[4]  <= \M_RX_0.samplex16_counter[4]_$_DFF_PN1__Q_D ;
  assign \M_RX_0.samplex16_counter[4]_$_DFF_PN1__Q_D  = \M_RX_0.samplex16_counter[4]_$_DFF_PN1__Q_D_$_OR__Y_A  | \M_RX_0.samplex16_counter[4]_$_OR__B_Y_$_NAND__A_Y ;
  assign \M_RX_0.samplex16_counter[4]_$_DFF_PN1__Q_D_$_OR__Y_A  = \M_RX_0.samplex16_counter[4]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A  ^ \M_RX_0.samplex16_counter[4] ;
  assign \M_RX_0.samplex16_counter[4]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A  = \M_RX_0.samplex16_counter[4]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A_$_ANDNOT__Y_A  & ~(\M_RX_0.samplex16_counter[3]_$_OR__B_Y );
  assign \M_RX_0.samplex16_counter[4]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A_$_ANDNOT__Y_A  = \M_RX_0.samplex16_counter[1]_$_NOR__A_Y  | ~(\M_RX_0.samplex16_counter[3]_$_NOR__B_Y );
  assign \M_RX_0.samplex16_counter[4]_$_OR__B_Y  = \M_RX_0.samplex16_counter[4]_$_OR__B_A  | \M_RX_0.samplex16_counter[4] ;
  assign \M_RX_0.samplex16_counter[4]_$_OR__B_1_Y  = \M_RX_0.samplex16_counter[4]_$_OR__B_1_A  | \M_RX_0.samplex16_counter[4] ;
  assign \M_RX_0.samplex16_counter[4]_$_OR__B_A  = ~(\M_RX_0.samplex16_counter[1]_$_NOR__A_Y  & \M_RX_0.samplex16_counter[3]_$_NOR__B_Y );
  assign \M_RX_0.samplex16_counter[4]_$_OR__B_Y_$_NAND__A_Y  = ~(\M_RX_0.samplex16_counter[4]_$_OR__B_Y  & \M_RX_0.samplex16_counter[4]_$_OR__B_1_Y );
  assign \M_RX_0.samplex16_counter[4]_$_OR__B_Y_$_NAND__A_Y_$_ORNOT__B_Y  = \M_RX_0.sample_counter[1]_$_OR__A_Y_$_MUX__A_Y  | ~(\M_RX_0.samplex16_counter[4]_$_OR__B_Y_$_NAND__A_Y );
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.shiftreg[0]  <= 1'h0;
    else if (\M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y ) \M_RX_0.shiftreg[0]  <= \M_RX_0.shiftreg[1] ;
  assign \M_RX_0.shiftreg[0]_$_XNOR__B_Y  = ~(\M_RX_0.shiftreg[1]  ^ \M_RX_0.shiftreg[0] );
  assign \M_RX_0.shiftreg[0]_$_XNOR__B_Y_$_XOR__B_Y  = \M_RX_0.shiftreg[2]_$_XNOR__B_Y  ^ \M_RX_0.shiftreg[0]_$_XNOR__B_Y ;
  assign \parity_err_$_ANDNOT__Y_B_$_OR__Y_A_$_XOR__Y_A  = \M_RX_0.shiftreg[4]_$_XOR__B_Y_$_XOR__B_Y  ^ \M_RX_0.shiftreg[0]_$_XNOR__B_Y_$_XOR__B_Y ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.shiftreg[1]  <= 1'h0;
    else if (\M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y ) \M_RX_0.shiftreg[1]  <= \M_RX_0.shiftreg[2] ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.shiftreg[2]  <= 1'h0;
    else if (\M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y ) \M_RX_0.shiftreg[2]  <= \M_RX_0.shiftreg[3] ;
  assign \M_RX_0.shiftreg[2]_$_XNOR__B_Y  = ~(\M_RX_0.shiftreg[3]  ^ \M_RX_0.shiftreg[2] );
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.shiftreg[3]  <= 1'h0;
    else if (\M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y ) \M_RX_0.shiftreg[3]  <= \M_RX_0.shiftreg[4] ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.shiftreg[4]  <= 1'h0;
    else if (\M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y ) \M_RX_0.shiftreg[4]  <= \M_RX_0.shiftreg[5] ;
  assign \M_RX_0.shiftreg[4]_$_XOR__B_Y  = \M_RX_0.shiftreg[5]  ^ \M_RX_0.shiftreg[4] ;
  assign \M_RX_0.shiftreg[4]_$_XOR__B_Y_$_XOR__B_Y  = \M_RX_0.shiftreg[6]_$_XNOR__B_Y  ^ \M_RX_0.shiftreg[4]_$_XOR__B_Y ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.shiftreg[5]  <= 1'h0;
    else if (\M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y ) \M_RX_0.shiftreg[5]  <= \M_RX_0.shiftreg[6] ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.shiftreg[6]  <= 1'h0;
    else if (\M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y ) \M_RX_0.shiftreg[6]  <= \M_RX_0.shiftreg[7] ;
  assign \M_RX_0.shiftreg[6]_$_XNOR__B_Y  = ~(\M_RX_0.shiftreg[7]  ^ \M_RX_0.shiftreg[6] );
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.shiftreg[7]  <= 1'h0;
    else if (\M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y ) \M_RX_0.shiftreg[7]  <= \M_RX_0.rx ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.state[0]  <= 1'h0;
    else if (\M_RX_0.state[2]_$_DFFE_PN0P__Q_E ) \M_RX_0.state[0]  <= \M_RX_0.nextstate[0] ;
  assign \M_RX_0.state[0]_$_NAND__A_Y  = ~(\M_RX_0.state[0]  & \M_RX_0.state[1] );
  assign \M_RX_0.state[0]_$_ORNOT__A_Y  = \M_RX_0.state[0]  | ~(\M_RX_0.state[1] );
  assign \M_RX_0.state[0]_$_ORNOT__A_Y_$_ANDNOT__B_Y  = \error_flag_$_NOT__Y_A_$_OR__Y_B  & ~(\M_RX_0.state[0]_$_ORNOT__A_Y );
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.state[1]  <= 1'h0;
    else if (\M_RX_0.state[2]_$_DFFE_PN0P__Q_E ) \M_RX_0.state[1]  <= \M_RX_0.nextstate[1] ;
  (* src = "src/UART_rx.v:29.1-76.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_RX_0.state[2]  <= 1'h0;
    else if (\M_RX_0.state[2]_$_DFFE_PN0P__Q_E ) \M_RX_0.state[2]  <= \M_RX_0.nextstate[2] ;
  assign \M_RX_0.state[2]_$_DFFE_PN0P__Q_E  = \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_A  & ~(\M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B );
  assign \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_A  = \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_A  & ~(\M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B );
  assign \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_A  = \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_A_$_ANDNOT__Y_A  & ~(\M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_A_$_ANDNOT__Y_B );
  assign \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_A_$_ANDNOT__Y_A  = ~(\M_RX_0.nextstate[1]_$_ORNOT__Y_A_$_OR__Y_B_$_ANDNOT__Y_A  & \M_RX_0.sample_counter[1]_$_OR__A_Y_$_MUX__A_Y );
  assign \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_A_$_ANDNOT__Y_B  = \M_RX_0.state[0]_$_ORNOT__A_Y_$_ANDNOT__B_Y  & \M_RX_0.sample_counter[1]_$_OR__A_Y_$_MUX__A_Y ;
  assign \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B  = \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__Y_A  | \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__Y_B ;
  assign \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__Y_A  = \error_flag_$_NOT__Y_A_$_OR__Y_A_$_ANDNOT__B_Y  & \M_RX_0.sample_counter[1]_$_OR__A_Y_$_MUX__A_Y ;
  assign \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__Y_B  = \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_A_$_OR__Y_A_$_ANDNOT__B_Y  & \M_RX_0.sample_counter[1]_$_OR__A_Y_$_MUX__A_Y ;
  assign \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B  = \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_OR__Y_A  | \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_OR__Y_B ;
  assign \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_OR__Y_A  = \M_RX_0.state[1]  & \M_RX_0.state[2] ;
  assign \error_flag_$_NOT__Y_A_$_OR__Y_B  = ~\M_RX_0.state[2] ;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_TX_0.count_tick[0]  <= 1'h0;
    else \M_TX_0.count_tick[0]  <= \M_TX_0.count_tick[0]_$_DFF_PN0__Q_D ;
  assign \M_TX_0.count_tick[0]_$_DFF_PN0__Q_D  = ~(\M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A_$_ANDNOT__B_Y_$_OR__B_Y  | \M_TX_0.count_tick[0] );
  (* src = "src/UART_tx.v:27.1-66.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_TX_0.count_tick[1]  <= 1'h0;
    else \M_TX_0.count_tick[1]  <= \M_TX_0.count_tick[1]_$_DFF_PN0__Q_D ;
  assign \M_TX_0.count_tick[1]_$_DFF_PN0__Q_D  = ~(\M_TX_0.count_tick[1]_$_DFF_PN0__Q_D_$_NOR__Y_A  | \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A_$_ANDNOT__B_Y_$_OR__B_Y );
  assign \M_TX_0.count_tick[1]_$_DFF_PN0__Q_D_$_NOR__Y_A  = \M_TX_0.count_tick[0]  ^ \M_TX_0.count_tick[1] ;
  assign \M_TX_0.count_tick[1]_$_NOR__B_Y  = ~(\M_TX_0.count_tick[0]  | \M_TX_0.count_tick[1] );
  assign \M_TX_0.count_tick[1]_$_ORNOT__A_Y  = \M_TX_0.count_tick[1]  | ~(\M_TX_0.count_tick[0] );
  (* src = "src/UART_tx.v:27.1-66.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_TX_0.count_tick[2]  <= 1'h1;
    else \M_TX_0.count_tick[2]  <= \M_TX_0.count_tick[2]_$_DFF_PN1__Q_D ;
  assign \M_TX_0.count_tick[2]_$_DFF_PN1__Q_D  = \M_TX_0.count_tick[2]_$_DFF_PN1__Q_D_$_OR__Y_A  | \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A_$_ANDNOT__B_Y_$_OR__B_Y ;
  assign \M_TX_0.count_tick[2]_$_DFF_PN1__Q_D_$_OR__Y_A  = \M_TX_0.count_tick[1]_$_NOR__B_Y  ^ \M_TX_0.count_tick[2] ;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_TX_0.count_tick[3]  <= 1'h0;
    else \M_TX_0.count_tick[3]  <= \M_TX_0.count_tick[3]_$_DFF_PN0__Q_D ;
  assign \M_TX_0.count_tick[3]_$_DFF_PN0__Q_D  = ~(\M_TX_0.count_tick[3]_$_DFF_PN0__Q_D_$_NOR__Y_A  | \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A_$_ANDNOT__B_Y_$_OR__B_Y );
  assign \M_TX_0.count_tick[3]_$_DFF_PN0__Q_D_$_NOR__Y_A  = ~(\M_TX_0.count_tick[3]_$_DFF_PN0__Q_D_$_NOR__Y_A_$_XNOR__Y_A  ^ \M_TX_0.count_tick[3] );
  assign \M_TX_0.count_tick[3]_$_DFF_PN0__Q_D_$_NOR__Y_A_$_XNOR__Y_A  = \M_TX_0.count_tick[1]_$_NOR__B_Y  & ~(\M_TX_0.count_tick[2] );
  assign \M_TX_0.count_tick[3]_$_NOR__A_Y  = ~(\M_TX_0.count_tick[3]  | \M_TX_0.count_tick[2] );
  assign \M_TX_0.count_tick[3]_$_OR__A_Y  = \M_TX_0.count_tick[3]  | \M_TX_0.count_tick[2] ;
  assign \M_TX_0.count_tick[3]_$_OR__A_Y_$_NOR__B_Y  = ~(\M_TX_0.count_tick[1]_$_NOR__B_Y  | \M_TX_0.count_tick[3]_$_OR__A_Y );
  assign \M_TX_0.count_tick[3]_$_OR__A_Y_$_OR__B_Y  = \M_TX_0.count_tick[1]_$_ORNOT__A_Y  | \M_TX_0.count_tick[3]_$_OR__A_Y ;
  assign \M_TX_0.count_tick[3]_$_OR__A_Y_$_OR__B_Y_$_OR__A_Y  = \M_TX_0.count_tick[3]_$_OR__A_Y_$_OR__B_Y  | \M_TX_0.count_tick[7]_$_NOR__B_Y_$_NAND__B_Y ;
  assign \M_TX_0.count_tick[3]_$_OR__A_Y_$_OR__B_Y_$_OR__A_Y_$_ANDNOT__B_Y  = \M_TX_0.count_tick[8]_$_NOT__A_Y  & ~(\M_TX_0.count_tick[3]_$_OR__A_Y_$_OR__B_Y_$_OR__A_Y );
  (* src = "src/UART_tx.v:27.1-66.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_TX_0.count_tick[4]  <= 1'h0;
    else \M_TX_0.count_tick[4]  <= \M_TX_0.count_tick[4]_$_DFF_PN0__Q_D ;
  assign \M_TX_0.count_tick[4]_$_DFF_PN0__Q_D  = ~(\M_TX_0.count_tick[4]_$_DFF_PN0__Q_D_$_NOR__Y_A  | \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A_$_ANDNOT__B_Y_$_OR__B_Y );
  assign \M_TX_0.count_tick[4]_$_NOR__B_Y  = ~(\M_TX_0.count_tick[5]  | \M_TX_0.count_tick[4] );
  assign \M_TX_0.count_tick[4]_$_NOT__A_Y  = ~\M_TX_0.count_tick[4] ;
  assign \M_TX_0.count_tick[5]_$_XOR__B_A  = \M_TX_0.count_tick[4]_$_NOT__A_Y  & ~(\M_TX_0.count_tick[4]_$_NOT__A_Y_$_ANDNOT__A_B );
  assign \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A_$_OR__Y_A  = \M_TX_0.count_tick[4]_$_NOT__A_Y_$_ANDNOT__A_B  & ~(\M_TX_0.count_tick[7]_$_NOR__B_Y_$_NAND__B_Y );
  assign \M_TX_0.count_tick[4]_$_NOT__A_Y_$_ANDNOT__A_B  = \M_TX_0.count_tick[3]_$_OR__A_Y_$_NOR__B_Y  | ~(\M_TX_0.count_tick[3]_$_NOR__A_Y );
  assign \M_TX_0.count_tick[4]_$_DFF_PN0__Q_D_$_NOR__Y_A  = \M_TX_0.count_tick[4]_$_NOT__A_Y_$_XOR__B_A  ^ \M_TX_0.count_tick[4]_$_NOT__A_Y ;
  assign \M_TX_0.count_tick[6]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XNOR__Y_A_$_ORNOT__Y_A  = \M_TX_0.count_tick[4]_$_NOR__B_Y  & ~(\M_TX_0.count_tick[4]_$_NOT__A_Y_$_XOR__B_A );
  assign \M_TX_0.count_tick[4]_$_NOT__A_Y_$_XOR__B_A  = \M_TX_0.count_tick[3]_$_NOR__A_Y  & ~(\M_TX_0.count_tick[3]_$_OR__A_Y_$_NOR__B_Y );
  (* src = "src/UART_tx.v:27.1-66.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_TX_0.count_tick[5]  <= 1'h1;
    else \M_TX_0.count_tick[5]  <= \M_TX_0.count_tick[5]_$_DFF_PN1__Q_D ;
  assign \M_TX_0.count_tick[5]_$_DFF_PN1__Q_D  = \M_TX_0.count_tick[5]_$_XOR__B_Y  | \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A_$_ANDNOT__B_Y_$_OR__B_Y ;
  assign \M_TX_0.count_tick[5]_$_XOR__B_Y  = \M_TX_0.count_tick[5]_$_XOR__B_A  ^ \M_TX_0.count_tick[5] ;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_TX_0.count_tick[6]  <= 1'h1;
    else \M_TX_0.count_tick[6]  <= \M_TX_0.count_tick[6]_$_DFF_PN1__Q_D ;
  assign \M_TX_0.count_tick[6]_$_DFF_PN1__Q_D  = \M_TX_0.count_tick[6]_$_DFF_PN1__Q_D_$_OR__Y_A  | \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A_$_ANDNOT__B_Y_$_OR__B_Y ;
  assign \M_TX_0.count_tick[6]_$_DFF_PN1__Q_D_$_OR__Y_A  = ~(\M_TX_0.count_tick[6]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XNOR__Y_A  ^ \M_TX_0.count_tick[6] );
  assign \M_TX_0.count_tick[6]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XNOR__Y_A  = \M_TX_0.count_tick[6]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XNOR__Y_A_$_ORNOT__Y_A  | ~(\M_TX_0.count_tick[4]_$_NOR__B_Y );
  (* src = "src/UART_tx.v:27.1-66.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_TX_0.count_tick[7]  <= 1'h0;
    else \M_TX_0.count_tick[7]  <= \M_TX_0.count_tick[7]_$_DFF_PN0__Q_D ;
  assign \M_TX_0.count_tick[7]_$_DFF_PN0__Q_D  = ~(\M_TX_0.count_tick[7]_$_DFF_PN0__Q_D_$_NOR__Y_A  | \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A_$_ANDNOT__B_Y_$_OR__B_Y );
  assign \M_TX_0.count_tick[7]_$_DFF_PN0__Q_D_$_NOR__Y_A  = \M_TX_0.count_tick[7]_$_DFF_PN0__Q_D_$_NOR__Y_A_$_XOR__Y_A  ^ \M_TX_0.count_tick[7] ;
  assign \M_TX_0.count_tick[7]_$_DFF_PN0__Q_D_$_NOR__Y_A_$_XOR__Y_A  = \M_TX_0.count_tick[6]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XNOR__Y_A  | \M_TX_0.count_tick[6] ;
  assign \M_TX_0.count_tick[7]_$_NOR__B_Y  = ~(\M_TX_0.count_tick[6]  | \M_TX_0.count_tick[7] );
  assign \M_TX_0.count_tick[7]_$_OR__B_Y_$_OR__B_A  = \M_TX_0.count_tick[7]_$_NOR__B_Y  & ~(\M_TX_0.count_tick[4]_$_NOR__B_Y );
  assign \M_TX_0.count_tick[7]_$_NOR__B_Y_$_NAND__B_Y  = ~(\M_TX_0.count_tick[4]_$_NOR__B_Y  & \M_TX_0.count_tick[7]_$_NOR__B_Y );
  assign \M_TX_0.count_tick[7]_$_OR__B_Y  = \M_TX_0.count_tick[6]  | \M_TX_0.count_tick[7] ;
  assign \M_TX_0.count_tick[7]_$_OR__B_Y_$_OR__B_Y  = \M_TX_0.count_tick[7]_$_OR__B_Y_$_OR__B_A  | \M_TX_0.count_tick[7]_$_OR__B_Y ;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_TX_0.count_tick[8]  <= 1'h1;
    else \M_TX_0.count_tick[8]  <= \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D ;
  assign \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D  = \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A  | \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A_$_ANDNOT__B_Y_$_OR__B_Y ;
  assign \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A  = \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A  ^ \M_TX_0.count_tick[8]_$_NOT__A_Y ;
  assign \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A_$_ANDNOT__B_Y  = \M_TX_0.count_tick[8]_$_NOT__A_Y  & ~(\M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A );
  assign \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A_$_ANDNOT__B_Y_$_OR__B_Y  = \M_TX_0.count_tick[3]_$_OR__A_Y_$_OR__B_Y_$_OR__A_Y_$_ANDNOT__B_Y  | \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A_$_ANDNOT__B_Y ;
  assign \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A  = \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A_$_OR__Y_A  | \M_TX_0.count_tick[7]_$_OR__B_Y_$_OR__B_Y ;
  assign \M_TX_0.count_tick[8]_$_NOT__A_Y  = ~\M_TX_0.count_tick[8] ;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_TX_0.datcount[0]  <= 1'h1;
    else if (\M_TX_0.datcount[2]_$_DFFE_PN1P__Q_E ) \M_TX_0.datcount[0]  <= \M_TX_0.datcount[0]_$_DFFE_PN1P__Q_D ;
  assign \M_TX_0.datcount[0]_$_DFFE_PN1P__Q_D  = \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__B_Y  | ~(\M_TX_0.datcount[0] );
  (* src = "src/UART_tx.v:27.1-66.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_TX_0.datcount[1]  <= 1'h1;
    else if (\M_TX_0.datcount[2]_$_DFFE_PN1P__Q_E ) \M_TX_0.datcount[1]  <= \M_TX_0.datcount[1]_$_DFFE_PN1P__Q_D ;
  assign \M_TX_0.datcount[1]_$_DFFE_PN1P__Q_D  = \M_TX_0.datcount[1]_$_DFFE_PN1P__Q_D_$_OR__Y_A  | \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__B_Y ;
  assign \M_TX_0.datcount[2]_$_XOR__B_A  = ~(\M_TX_0.datcount[1]  | \M_TX_0.datcount[0] );
  assign \M_TX_0.datcount[2]_$_NOR__B_A  = \M_TX_0.datcount[1]  | \M_TX_0.datcount[0] ;
  assign \M_TX_0.datcount[1]_$_DFFE_PN1P__Q_D_$_OR__Y_A  = ~(\M_TX_0.datcount[1]  ^ \M_TX_0.datcount[0] );
  (* src = "src/UART_tx.v:27.1-66.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_TX_0.datcount[2]  <= 1'h1;
    else if (\M_TX_0.datcount[2]_$_DFFE_PN1P__Q_E ) \M_TX_0.datcount[2]  <= \M_TX_0.datcount[2]_$_DFFE_PN1P__Q_D ;
  assign \M_TX_0.datcount[2]_$_DFFE_PN1P__Q_D  = \M_TX_0.datcount[2]_$_XOR__B_Y  | \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__B_Y ;
  assign \M_TX_0.datcount[2]_$_DFFE_PN1P__Q_E  = \M_TX_0.datcount[2]_$_DFFE_PN1P__Q_E_$_AND__Y_A  & \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A_$_ANDNOT__B_Y_$_OR__B_Y ;
  assign \M_TX_0.datcount[2]_$_DFFE_PN1P__Q_E_$_AND__Y_A_$_ANDNOT__B_Y  = \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_A_$_MUX__Y_A_$_OR__A_Y  & ~(\M_TX_0.datcount[2]_$_DFFE_PN1P__Q_E_$_AND__Y_A );
  assign \M_TX_0.datcount[2]_$_DFFE_PN1P__Q_E_$_AND__Y_A  = \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y  | \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__B_Y ;
  assign \M_TX_0.datcount[2]_$_NOR__B_Y  = ~(\M_TX_0.datcount[2]_$_NOR__B_A  | \M_TX_0.datcount[2] );
  assign \M_TX_0.nextstate[0]_$_MUX__Y_A_$_ORNOT__Y_A  = \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y  & ~(\M_TX_0.datcount[2]_$_NOR__B_Y );
  assign \M_TX_0.datcount[2]_$_XOR__B_Y  = \M_TX_0.datcount[2]_$_XOR__B_A  ^ \M_TX_0.datcount[2] ;
  assign \M_TX_0.nextstate[0]  = \M_TX_0.datcount[2]_$_DFFE_PN1P__Q_E_$_AND__Y_A_$_ANDNOT__B_Y  ? tx_enable : \M_TX_0.nextstate[0]_$_MUX__Y_A ;
  assign \M_TX_0.nextstate[0]_$_MUX__Y_A  = \M_TX_0.nextstate[0]_$_MUX__Y_A_$_ORNOT__Y_A  | ~(\M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_A_$_MUX__Y_A_$_OR__A_Y );
  assign \M_TX_0.nextstate[1]  = \M_TX_0.nextstate[1]_$_ANDNOT__Y_A  & ~(\M_TX_0.datcount[2]_$_DFFE_PN1P__Q_E_$_AND__Y_A_$_ANDNOT__B_Y );
  assign \M_TX_0.nextstate[1]_$_ANDNOT__Y_A  = \M_TX_0.nextstate[1]_$_ANDNOT__Y_A_$_ORNOT__Y_A  | ~(\M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_A_$_MUX__Y_A_$_OR__A_Y );
  assign \M_TX_0.nextstate[1]_$_ANDNOT__Y_A_$_ORNOT__Y_A  = \M_TX_0.nextstate[0]_$_MUX__Y_A_$_ORNOT__Y_A  | \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__B_Y ;
  assign \M_TX_0.nextstate[2]  = \M_TX_0.nextstate[2]_$_ANDNOT__Y_A  & ~(\M_TX_0.datcount[2]_$_DFFE_PN1P__Q_E_$_AND__Y_A_$_ANDNOT__B_Y );
  assign \M_TX_0.nextstate[2]_$_ANDNOT__Y_A  = \M_TX_0.datcount[2]_$_NOR__B_Y  & \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y ;
  assign \M_TX_0.parity_bit_$_AND__B_Y  = \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__B_Y  & \M_TX_0.parity_bit ;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  always @(posedge clkgen)
    if (\M_TX_0.parity_bit_$_DFFE_PP__Q_E ) \M_TX_0.parity_bit  <= \M_TX_0.parity_bit_$_DFFE_PP__Q_D ;
  assign \M_TX_0.parity_bit_$_DFFE_PP__Q_D  = \M_TX_0.parity_bit_$_DFFE_PP__Q_D_$_XOR__Y_A  ^ \M_TX_0.parity_bit_$_DFFE_PP__Q_D_$_XOR__Y_B ;
  assign \M_TX_0.parity_bit_$_DFFE_PP__Q_E  = \M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A  & ~(\M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_A_$_MUX__Y_A_$_OR__A_Y );
  assign \M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A  = \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A_$_ANDNOT__B_Y_$_OR__B_Y  & ~(\M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B );
  assign \M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B  = ~reset;
  assign \M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__B_Y  = \M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__B_A  | \M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B ;
  assign \M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__B_A  = \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_A  & ~(\M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y );
  assign \M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__B_Y_$_ANDNOT__B_Y  = \M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__B_Y_$_ANDNOT__B_A  & ~(\M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__B_Y );
  assign \M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__B_Y_$_ANDNOT__B_A  = \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A_$_ANDNOT__B_Y_$_OR__B_Y  & ~(\M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__B_Y_$_ANDNOT__B_A_$_ANDNOT__Y_B );
  assign \M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__B_Y_$_ANDNOT__B_A_$_ANDNOT__Y_B  = \M_TX_0.state[2]  | ~(\M_TX_0.state[0] );
  assign \M_TX_0.shiftreg[0]_$_AND__B_Y  = \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y  & \M_TX_0.shiftreg[0] ;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  always @(posedge clkgen)
    if (\M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__B_Y_$_ANDNOT__B_Y ) \M_TX_0.shiftreg[0]  <= \M_TX_0.shiftregnext[0] ;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  always @(posedge clkgen)
    if (\M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__B_Y_$_ANDNOT__B_Y ) \M_TX_0.shiftreg[1]  <= \M_TX_0.shiftregnext[1] ;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  always @(posedge clkgen)
    if (\M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__B_Y_$_ANDNOT__B_Y ) \M_TX_0.shiftreg[2]  <= \M_TX_0.shiftregnext[2] ;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  always @(posedge clkgen)
    if (\M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__B_Y_$_ANDNOT__B_Y ) \M_TX_0.shiftreg[3]  <= \M_TX_0.shiftregnext[3] ;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  always @(posedge clkgen)
    if (\M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__B_Y_$_ANDNOT__B_Y ) \M_TX_0.shiftreg[4]  <= \M_TX_0.shiftregnext[4] ;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  always @(posedge clkgen)
    if (\M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__B_Y_$_ANDNOT__B_Y ) \M_TX_0.shiftreg[5]  <= \M_TX_0.shiftregnext[5] ;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  always @(posedge clkgen)
    if (\M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__B_Y_$_ANDNOT__B_Y ) \M_TX_0.shiftreg[6]  <= \M_TX_0.shiftregnext[6] ;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  always @(posedge clkgen)
    if (\M_TX_0.parity_bit_$_DFFE_PP__Q_E_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__B_Y_$_ANDNOT__B_Y )
      if (\M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y ) \M_TX_0.shiftreg[7]  <= 1'h0;
      else \M_TX_0.shiftreg[7]  <= \data_tx[7] ;
  assign \M_TX_0.shiftregnext[0]  = \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y  ? \M_TX_0.shiftreg[1]  : \data_tx[0] ;
  assign \M_TX_0.shiftregnext[1]  = \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y  ? \M_TX_0.shiftreg[2]  : \data_tx[1] ;
  assign \M_TX_0.shiftregnext[2]  = \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y  ? \M_TX_0.shiftreg[3]  : \data_tx[2] ;
  assign \M_TX_0.shiftregnext[3]  = \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y  ? \M_TX_0.shiftreg[4]  : \data_tx[3] ;
  assign \M_TX_0.shiftregnext[4]  = \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y  ? \M_TX_0.shiftreg[5]  : \data_tx[4] ;
  assign \M_TX_0.shiftregnext[5]  = \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y  ? \M_TX_0.shiftreg[6]  : \data_tx[5] ;
  assign \M_TX_0.shiftregnext[6]  = \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y  ? \M_TX_0.shiftreg[7]  : \data_tx[6] ;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_TX_0.state[0]  <= 1'h0;
    else if (\M_TX_0.state[0]_$_DFFE_PN0P__Q_E ) \M_TX_0.state[0]  <= \M_TX_0.nextstate[0] ;
  assign \M_TX_0.state[0]_$_DFFE_PN0P__Q_E  = \M_TX_0.count_tick[8]_$_DFF_PN1__Q_D_$_OR__Y_A_$_XOR__Y_A_$_ANDNOT__B_Y_$_OR__B_Y  & ~(\M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B );
  assign \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B  = \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A  & ~(\M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B );
  assign \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A  = \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_A  & ~(\M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_B );
  assign \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_A  = \M_TX_0.state[2]  ? \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_B  : \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_A_$_MUX__Y_A ;
  assign \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_A_$_MUX__Y_A  = \M_TX_0.state[1]  | ~(\M_TX_0.state[0] );
  assign \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_A_$_MUX__Y_A_$_OR__A_Y  = \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_A_$_MUX__Y_A  | \M_TX_0.state[2] ;
  assign \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_B  = \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__Y_A  | \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y ;
  assign \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__Y_A  = \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_A  & ~(\M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__Y_A_$_ANDNOT__Y_B );
  assign \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__Y_B_$_OR__Y_A_$_ANDNOT__Y_B  = \M_TX_0.state[0]  | ~(\M_TX_0.state[1] );
  assign \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B  = \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_A  & ~(\M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_B );
  assign \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_Y  = \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_A  & ~(\M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_B );
  assign \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_A_$_ANDNOT__A_B  = ~(\M_TX_0.state[1]  & \M_TX_0.state[0] );
  assign \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_A  = ~\M_TX_0.state[2] ;
  assign \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__B_Y  = \M_TX_0.state[2]  & ~(\M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_B );
  assign \M_TX_0.state[0]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_ANDNOT__Y_B_$_ANDNOT__Y_B  = \M_TX_0.state[1]  | \M_TX_0.state[0] ;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_TX_0.state[1]  <= 1'h0;
    else if (\M_TX_0.state[0]_$_DFFE_PN0P__Q_E ) \M_TX_0.state[1]  <= \M_TX_0.nextstate[1] ;
  (* src = "src/UART_tx.v:27.1-66.4" *)
  always @(posedge clkgen, negedge reset)
    if (!reset) \M_TX_0.state[2]  <= 1'h0;
    else if (\M_TX_0.state[0]_$_DFFE_PN0P__Q_E ) \M_TX_0.state[2]  <= \M_TX_0.nextstate[2] ;
  assign \data_tx[0]_$_XOR__B_Y  = \data_tx[1]  ^ \data_tx[0] ;
  assign \M_TX_0.parity_bit_$_DFFE_PP__Q_D_$_XOR__Y_B  = \data_tx[2]_$_XNOR__B_Y  ^ \data_tx[0]_$_XOR__B_Y ;
  assign \data_tx[2]_$_XNOR__B_Y  = ~(\data_tx[3]  ^ \data_tx[2] );
  assign \data_tx[4]_$_XOR__B_Y  = \data_tx[5]  ^ \data_tx[4] ;
  assign \M_TX_0.parity_bit_$_DFFE_PP__Q_D_$_XOR__Y_A  = \data_tx[6]_$_XNOR__B_Y  ^ \data_tx[4]_$_XOR__B_Y ;
  assign \data_tx[6]_$_XNOR__B_Y  = ~(\data_tx[7]  ^ \data_tx[6] );
  assign error_flag = ~\error_flag_$_NOT__Y_A ;
  assign \error_flag_$_NOT__Y_A_$_ANDNOT__A_Y  = \error_flag_$_NOT__Y_A  & ~(\M_RX_0.rx_prev_$_ANDNOT__A_Y );
  assign \error_flag_$_NOT__Y_A_$_ANDNOT__A_Y_$_ANDNOT__A_Y  = \error_flag_$_NOT__Y_A_$_ANDNOT__A_Y  & ~(\error_flag_$_NOT__Y_A_$_ANDNOT__A_Y_$_ANDNOT__A_B );
  assign \error_flag_$_NOT__Y_A_$_ANDNOT__A_Y_$_ANDNOT__A_B  = \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_A_$_OR__Y_A_$_ANDNOT__B_Y  | \error_flag_$_NOT__Y_A_$_OR__Y_A_$_ANDNOT__B_Y ;
  assign \error_flag_$_NOT__Y_A_$_ANDNOT__A_Y_$_ANDNOT__A_Y_$_ANDNOT__A_Y  = \error_flag_$_NOT__Y_A_$_ANDNOT__A_Y_$_ANDNOT__A_Y  & ~(\error_flag_$_NOT__Y_A_$_ANDNOT__A_Y_$_ANDNOT__A_Y_$_ANDNOT__A_B );
  assign \error_flag_$_NOT__Y_A_$_ANDNOT__A_Y_$_ANDNOT__A_Y_$_ANDNOT__A_B  = \M_RX_0.state[1]  & ~(\M_RX_0.state[2] );
  assign \M_RX_0.state[2]_$_DFFE_PN0P__Q_E_$_ANDNOT__Y_B_$_OR__Y_B  = \error_flag_$_NOT__Y_A_$_ANDNOT__A_Y_$_ANDNOT__A_Y_$_ANDNOT__A_Y  | ~(\M_RX_0.samplex16_counter[4]_$_OR__B_Y_$_NAND__A_Y );
  assign \error_flag_$_NOT__Y_A  = \error_flag_$_NOT__Y_A_$_OR__Y_A  | \error_flag_$_NOT__Y_A_$_OR__Y_B ;
  assign \error_flag_$_NOT__Y_A_$_OR__Y_A_$_ANDNOT__B_Y  = \error_flag_$_NOT__Y_A_$_OR__Y_B  & ~(\error_flag_$_NOT__Y_A_$_OR__Y_A );
  assign \error_flag_$_NOT__Y_A_$_OR__Y_A  = \M_RX_0.state[1]  | ~(\M_RX_0.state[0] );
  assign parity_err = \M_RX_0.rx_prev_$_ANDNOT__A_Y_$_NOR__B_A_$_OR__Y_A_$_ANDNOT__B_Y  & ~(\parity_err_$_ANDNOT__Y_B );
  assign \parity_err_$_ANDNOT__Y_B  = \parity_err_$_ANDNOT__Y_B_$_OR__Y_A  | \M_RX_0.sample_counter[1]_$_OR__A_Y_$_MUX__A_Y ;
  assign \parity_err_$_ANDNOT__Y_B_$_OR__Y_A  = \parity_err_$_ANDNOT__Y_B_$_OR__Y_A_$_XOR__Y_A  ^ \M_RX_0.rx ;
  assign rx_done = ~\rx_done_$_NOT__Y_A ;
  assign \rx_done_$_NOT__Y_A_$_ANDNOT__B_Y  = \M_RX_0.samplex16_counter[4]_$_OR__B_Y_$_NAND__A_Y  & ~(\rx_done_$_NOT__Y_A );
  assign \rx_done_$_NOT__Y_A  = \rx_done_$_NOT__Y_A_$_OR__Y_A  | \rx_done_$_NOT__Y_A_$_OR__Y_B ;
  assign \rx_done_$_NOT__Y_A_$_OR__Y_A  = \M_RX_0.sample_counter[1]_$_OR__A_Y_$_MUX__A_Y  | ~(\M_RX_0.rx );
  assign \rx_done_$_NOT__Y_A_$_OR__Y_B  = ~\error_flag_$_NOT__Y_A_$_OR__Y_A_$_ANDNOT__B_Y ;
  assign \rx_done_$_NOT__Y_A_$_OR__Y_B_$_ORNOT__B_Y  = \rx_done_$_NOT__Y_A_$_OR__Y_B_$_ORNOT__B_A  | ~(\rx_done_$_NOT__Y_A_$_OR__Y_B );
  assign \rx_done_$_NOT__Y_A_$_OR__Y_B_$_ORNOT__B_Y_$_NOR__A_Y  = ~(\rx_done_$_NOT__Y_A_$_OR__Y_B_$_ORNOT__B_Y  | \M_RX_0.state[0]_$_ORNOT__A_Y_$_ANDNOT__B_Y );
  assign \M_RX_0.sample_counter_next[3]_$_NOR__Y_A_$_ANDNOT__Y_A_$_ANDNOT__Y_A  = \M_RX_0.sample_counter[3]_$_XNOR__B_Y  | \rx_done_$_NOT__Y_A_$_OR__Y_B ;
  assign tx = \tx_$_OR__Y_A  | \M_TX_0.datcount[2]_$_DFFE_PN1P__Q_E_$_AND__Y_A_$_ANDNOT__B_Y ;
  assign \tx_$_OR__Y_A  = \M_TX_0.shiftreg[0]_$_AND__B_Y  | \M_TX_0.parity_bit_$_AND__B_Y ;
  assign \M_TX_0.data_in[7]  = \data_tx[7] ;
  assign \M_TX_0.data_in[6]  = \data_tx[6] ;
  assign \M_TX_0.data_in[5]  = \data_tx[5] ;
  assign \M_TX_0.data_in[4]  = \data_tx[4] ;
  assign \M_TX_0.data_in[3]  = \data_tx[3] ;
  assign \M_TX_0.data_in[2]  = \data_tx[2] ;
  assign \M_TX_0.data_in[1]  = \data_tx[1] ;
  assign \M_TX_0.data_in[0]  = \data_tx[0] ;
  assign \M_TX_0.shiftregnext[7]  = 1'hx;
  assign \data_rx[7]  = \M_RX_0.data_out[7] ;
  assign \data_rx[6]  = \M_RX_0.data_out[6] ;
  assign \data_rx[5]  = \M_RX_0.data_out[5] ;
  assign \data_rx[4]  = \M_RX_0.data_out[4] ;
  assign \data_rx[3]  = \M_RX_0.data_out[3] ;
  assign \data_rx[2]  = \M_RX_0.data_out[2] ;
  assign \data_rx[1]  = \M_RX_0.data_out[1] ;
  assign \data_rx[0]  = \M_RX_0.data_out[0] ;
  assign \M_TX_0.clkin  = clkgen;
  assign \M_TX_0.reset  = reset;
  assign \M_TX_0.TX_enable  = tx_enable;
  assign \M_TX_0.data_out  = tx;
  assign \M_RX_0.data_in  = rx;
  assign \M_RX_0.clkin  = clkgen;
  assign \M_RX_0.reset  = reset;
  assign \M_RX_0.error_flag  = error_flag;
  assign \M_RX_0.rx_done  = rx_done;
  assign \M_RX_0.parity_err  = parity_err;
endmodule
